### ISSUE TITLE
Configuration of procedure API

### ISSUE THREAD

**Issue by knutwalker** [neo4j-contrib/neo4j-graph-algorithms#16]
The test procedures at https://github.com/neo4j-contrib/neo4j-graph-algorithms/blob/607ec2c03ae57fd0edca75f25da3b6ad4177361d/algo/src/main/java/org/neo4j/graphalgo/impl/TestProcedure.java have unsafe configurability.
- parallelism is done by a copied procedure of a different name but should instead be a config parameter
- there is no validation of parameters
- there are no default parameters

**Comment by jexp** [comment]
The general approach for procedures: **one procedure per algorithm**

- one procedure per algorithm
- use relevant algorithm parameters (like iterations) as regular parameters
- don't leak implementation details in procedure name or regular parameters
- use default values where possible
- move implementation configuration into a config parameter of type `Map<String,Object>`
-- e.g. choice and configuration of loader, type of memory graph implementation, write-back, parallellism, etc. with sensible defaults

**Comment by knutwalker** [comment]
We have now proper procedures for every graph. If something's missing, I suggest a new issue for this.
