### ISSUE TITLE
Load input for Graphs via Cypher

### ISSUE THREAD

**Issue by knutwalker** [neo4j-contrib/neo4j-graph-algorithms#18]
Instead of allocating a List\<Node\> from Cypher while calling the procedure, we can accept a Cypher statement and run it ourselves, using the far more efficient PLongIterators.

**Comment by jexp** [comment]
Look at the implementation apoc's pageRankWithCypher

- one statement for the relationships
- `MATCH (a)-->(b)<--(c:Label3) RETURN id(a) as source, id(c) as target [, count/sum/...(*) as weight]`
- `db.execute(statement).visit(ResultVisitor)`
- extracts nodes on the fly from relationships
- use compiled runtime if possible
- batching -> increase skip-parameter by batch-size: `MATCH (a:Label1) WITH a SKIP {skip} limit 100000 MATCH (a)-->(b)<--(c:Label3) RETURN id(a) as source, id(c) as target`
- > perf-test if batching is worth it vs. compiled runtime / hand-off population to threads
- cypher's interpreted runtime it slow/memory intensive with large aggregation -> internal aggregation (currently only add up values, which works for count + sum) 
- > `MATCH (a)-->(b)<--(c:Label3) RETURN id(a) as source, id(c) as target, 1 as weight`
- > `MATCH (a)-->(b:Amount)<--(c:Label3) RETURN id(a) as source, id(c) as target, b.value as weight`
