### ISSUE TITLE
Add progress logging

### ISSUE THREAD

**Issue by jexp** [neo4j-contrib/neo4j-graph-algorithms#218]
for:

- [x] loading
- [x] algorithm execution
- [x] writing back

We should add some debug logging for these long running algos, 
either generically in ParallelUtil (e.g. a debug output every 10 seconds with some progress) or in the algos, we could have a central logger that keeps the last timestamp per "source" so that people see how far it has gotten.

Martin Knobloch can we get a logging instance at runtime without passing the Log object into each algorithm ?
and is it possible to activate log output using the embeddedDb in unitTests ?

Martin Knobloch because otherwise we would have to pass the Log from the procedure to each algorithm therefore we would have to adapt procs, alghorithm ctor signatures, tests

Martin Knobloch and i added some log output to one or two tests but didnt see anything in the tests

Michael Hunger to get the logger from the kernel via resolveDependency and pass it to ParallelUtil and the GraphFactory

Cleanest way would be:

- get log via @Context in procedure
- pass to graph factory and exporter via fluent API
- (while migrating) algorithm could use the graph for logging (via interface)
- later we can pass the Logger interface directly to each procedure

**Comment by mknblch** [comment]
Some algorithms do not use the Graph interface but the api2 sources. The GraphLoader/Factoriy is not involved in every algorithm (see MST for example). And ParallelUtil is a bunch of static functions. Therefore we would have to do the refactoring anyway. 

In conclusion it is not possible for us to get the Logger through some injection magic.

My suggestion would be to create some kind of abstract class for algorithms which does not pretend any ctor signature but adds a NullObject-Logger (or sysout logger) by default and some fluent setters for it. This would safe us from adapting each unit-test ( until we test the logging itself ) but we could easily pass the logger object from the procedure to the algo instance.
The Exporter itself is already an abstract class so there is no problem.

**Comment by mknblch** [comment]
Progress Logging is implemented in load, eval and write logic (where possible) using a interval of 10s for each log now. Due to the inaccuracy of the progress-calculation the values should be understood as approximation rather then exact values.

**Comment by mknblch** [comment]
We should do some tests on a bigger graph for each algorithm. Im a bit concernded about the current interval of 10s which might be cool for the user if he's watching the log but it does polute log files if those algorithms run in a backend of a service or so. 

We could also think about lowering the LogLevel of the ProgressLogger or we could make interval and/or loglevel changable in the config.

**Comment by mknblch** [comment]
implemented in loading, eval and write back
