### ISSUE TITLE
2x Pools

### ISSUE THREAD

**Issue by mknblch** [neo4j-contrib/neo4j-graph-algorithms#237]
Seems like we have still 2 implementations of the Pools-class. One `org.neo4j.graphalgo.Pools` and the other one `org.neo4j.graphalgo.core.utils.Pools`. Remove old - keep the newer one

**Comment by knutwalker** [comment]
the newer one is actually `org.neo4j.graphalgo.core.utils.Pools`, which was introduced in #178 and `org.neo4j.graphalgo.Pools` was copied from the apoc procedures in 2473170

**Comment by mknblch** [comment]
fix in #238
