### ISSUE TITLE
Label Propagation for undirected graph

### ISSUE THREAD

**Issue by johnymontana** [neo4j-contrib/neo4j-graph-algorithms#289]
When running `algo.labelPropagation` I want the graph to be treated as undirected. Is it possible to considered relationships in both directions?

~~~
CALL algo.labelPropagation('Character', 'INTERACTS', 'BOTH', {iterations:1000, weightProperty:'nweight', partitionProperty:'community', write:true})
~~~

> Failed to invoke procedure `algo.labelPropagation`: Caused by: java.lang.IllegalArgumentException: Direction BOTH is not allowed. Legal values are '[OUTGOING, INCOMING]'.

**Comment by ajkl** [comment]
Would `direction` as in https://github.com/neo4j-contrib/neo4j-graph-algorithms/pull/345 be a standard param for all graph algorithms eventually ?

**Comment by tomasonjo** [comment]
Sure...
You can check the versions part of the docs to check which all the version we should support (my opinion).

If you think something is missing somewhere please let us know!

Example for pagerank:
https://github.com/neo4j-contrib/neo4j-graph-algorithms/blob/3.1/doc/pagerank.adoc#versions
