### ISSUE TITLE
Write results of algorithms to the graph

### ISSUE THREAD

**Issue by knutwalker** [neo4j-contrib/neo4j-graph-algorithms#31]
Some algorithms operate on all nodes (e.g. PageRank) and instead of returning a large list of results, we should write the result back to the graph. Writes can be be partitioned which makes them [embarrassingly parallel](https://en.wikipedia.org/wiki/Embarrassingly_parallel).

**Comment by jexp** [comment]
Current Algorithm for writing back properties: https://github.com/neo4j-contrib/neo4j-graph-algorithms/blob/3.1/algo/src/main/java/algo/algo/algorithms/AlgoUtils.java#L63

Works well for
- setting properties
- creating nodes
- setting labels

For creating relationships we have to watch out for conflicts
-> smaller batch-size
-> retries with back-off
