### ISSUE TITLE
Add clustering coefficient to triangle procedures 

### ISSUE THREAD

**Issue by jexp** [neo4j-contrib/neo4j-graph-algorithms#334]
The local clustering coefficient of a node v is defined as the likeliness that two neighbors u and w of v are also connected, while the clustering coefficient of a graph is just the normalized sum of the clustering coefficient of its nodes. 
Accordingly, its computation involves counting the number of triangles. 

-> triangles / degree

Similarly, the transitivity coefficient of a graph, which is just three times the number of triangles divided by the number of triples (paths of length two) in the graph is sometimes considered.[2] 

-> triples are just pairs of neighbors, probably count them twice for each flip ??
-> so count of (3*) triangles / triples  per node and then globally

@tomasonjo

**Comment by tomasonjo** [comment]
Maybe this will be useful as well.

http://pages.stat.wisc.edu/~karlrohe/netsci/MeasuringTrianglesInGraphs.pdf

**Comment by mknblch** [comment]
@ #343
