### ISSUE TITLE
labelPropagation with initial labels

### ISSUE THREAD

**Issue by ghazale-hnt** [neo4j-contrib/neo4j-graph-algorithms#342]
It would be nice to be able to run labelPropagation on a graph with some initial labels assigned either manually or in previous runs of labelPropagation.

As talked in slack, we need an option to load the labels from the graph instead of rewriting them.

**Comment by jexp** [comment]
Good idea.

So we could allow a property to read the initial "label/cluster" values from which could incidentally be the same as then is written to, if the property is not configured we would do as we do right now.

**Comment by mknblch** [comment]
You can use _partitionProperty_ for initial labels.

CALL algo.labelPropagation(label:String, relationship:String, direction:String {iterations:1, weightProperty:'weight', **partitionProperty:'partition'** , write:true}) YIELD nodes, iterations, loadMillis, computeMillis, writeMillis, write, weightProperty, partitionProperty

**Comment by jexp** [comment]
Ah cool, I forgot about that one.

**Comment by ghazale-hnt** [comment]
ok that's perfect :+1:  thanks.
