### ISSUE TITLE
Betwenness centrality returns negative values 

### ISSUE THREAD

**Issue by tomasonjo** [neo4j-contrib/neo4j-graph-algorithms#349]
I used the [facebook friend list](https://snap.stanford.edu/data/egonets-Facebook.html) (Edges from all egonets combined) to test out triangles and undirected betwenness. 

Import:

```
USING PERIODIC COMMIT 5000
LOAD CSV FROM "file:///facebook_combined.txt" as row fieldterminator ' '
MERGE (u:User{id:row[0]})
MERGE (u1:User{id:row[1]})
MERGE (u)-[:FRIEND]-(u1)
```

When i run betwenness centrality with any direction, all of the versions contain negative values.
I think that betwenness algorithm should not return negative values based on the definition.
```
CALL algo.betweenness('User', 'FRIEND', {direction:'both',write:true, stats:true, writeProperty:'centrality',concurrency: 4}) 
YIELD nodes, minCentrality, maxCentrality, sumCentrality, loadMillis, computeMillis, writeMillis
```

results: 

![negative](https://user-images.githubusercontent.com/19948365/30006382-999a6e6e-90f7-11e7-9c31-a549d2496847.png)

Some further checks:
```
MATCH (n:User) RETURN n.id,n.triangles,n.centrality ORDER by n.centrality asc limit 20
```
return 

![further](https://user-images.githubusercontent.com/19948365/30006421-4f9e052c-90f8-11e7-9e4b-e4a6eccd79c6.png)

**Comment by mknblch** [comment]
this looks strange .. im going to check this

**Comment by mknblch** [comment]
Update: I added a test to reproduce the error. It seems negative values only occur when using the Procedure. A test directly on the Graph led to correct values.

**Comment by mknblch** [comment]
Update: only ParallelBC is affevted

**Comment by mknblch** [comment]
The Problem is a silent integer overflow in the scaling logic of `org.neo4j.graphalgo.core.utils.AtomicDoubleArray`. When we set a value we multiply it by the `slaceFactor` (default is 100_000) and sum it up in the AtomicIntegerArray. During this routine an intereger overflow happens and negates the values.

**Comment by mknblch** [comment]
Bug is adresses in #353
