### ISSUE TITLE
Provide support for 3.2 and 3.3

### ISSUE THREAD

**Issue by jexp** [neo4j-contrib/neo4j-graph-algorithms#359]
Make sure that we update the 3.2 branch to use  the current kernel api with iterators

After that and when 3.2 branch is updated with all latest changes (including huge-graph and new algorithms / bugfixes), fork off a 3.3 branch on the latest beta/RC

**Comment by knutwalker** [comment]
I'd say with the latest release on both, 3.2 and 3.3, we can close this ticket.
