### ISSUE TITLE
closeness centrality by default uses concurrency 1

### ISSUE THREAD

**Issue by jexp** [neo4j-contrib/neo4j-graph-algorithms#395]
Mark was testing and he had to pass in explicitely higher concurrency values

Please also check for betweennessCentrality and others

**Comment by tomasonjo** [comment]
betweennessCentrality has explicitly set to use unparallel algo unless stated otherwise:

```
  if (configuration.getConcurrency(-1) > 1) {
            return computeBetweennessParallel(label, relationship, configuration);
        } else {
            return computeBetweenness(label, relationship, configuration);
        }  
```

all the others defaults to 

```
int DEFAULT_CONCURRENCY = Runtime.getRuntime().availableProcessors();
```
I will add this to syntax docs... should the betwenness also become parallel as default ?

**Comment by knutwalker** [comment]
CC concurrency was already added in https://github.com/neo4j-contrib/neo4j-graph-algorithms/commit/f825a427141fbbe0733e977cc10b8b496c18c884#diff-b21643b8f21700be1d919c0ec6b86cf6, BC defaults to single threaded as @tomasonjo pointed out. @mknblch is there a particular reason to default to the single threaded BC or could we change it to default to the parallel one?

**Comment by jexp** [comment]
@knutwalker let's default it to the parallel one.
