### ISSUE TITLE
General-purpose, power procedure

### ISSUE THREAD

**Issue by jexp** [neo4j-contrib/neo4j-graph-algorithms#40]
This general purpose procedure allows loading the graph once and then allows multiple, differently configured algorithms on top of it, e.g. also page-rank with different configs or page-rank and clustering

### procedure pipelines

We can also consider one algorithm feeding into the next. E.g. the first-page-rank is not (just) persisted into the graph but immediately (with the in-memory computed values) taken into account for the next algorithm (centrality or clustering)

**Comment by knutwalker** [comment]
related to #201

**Comment by mneedham** [comment]
Done in https://github.com/neo4j-contrib/neo4j-graph-algorithms/commit/836f5f366a7fec46f9380cf56091f98627cca3e9
