### ISSUE TITLE
Close the impermanent database properly (or, at all)

### ISSUE THREAD

**Issue by knutwalker** [neo4j-contrib/neo4j-graph-algorithms#416]
Starting from 3.3 test start to fail.

> you need to shutdown your impermanent db, otherwise is will hold a lock on a store and will prevent next test to run
> or make sure that folder is random for each impermanent db that you starting

It's a good idea to to this for 3.2 and 3.1 as well

**Comment by knutwalker** [comment]
probably best to use the provided junit rule for the impermanent database, see https://github.com/neo4j-contrib/neo4j-graph-algorithms/blob/1ec4087da8f4e2c2abe5d9ead3e9132e609700a9/tests/src/test/java/org/neo4j/graphalgo/core/huge/HugeGraphWeightTest.java#L27-L28

**Comment by mknblch** [comment]
Seems like every testcase has a suitable TearDown method. Why is this ticket still open

**Comment by jexp** [comment]
We can close it. Going fwd we should use Pauls impermanentdbrule.
