### ISSUE TITLE
Louvain iteration problem ?

### ISSUE THREAD

**Issue by tomasonjo** [neo4j-contrib/neo4j-graph-algorithms#425]
I have tested the data from https://github.com/neo4j-contrib/neo4j-graph-algorithms/issues/398 and some other data and there is always less communities in gephi than in our algo. For this specific data we get 21 communities and gephi gets 7 with default modularity 1.0. We are consistently getting more communities than gephi. I ran a couple of different options and with up to 4k nodes and 90k rels and always got only 1 iteration and I think this might be the problem as I have never seen 2 iterations happens so far.

**Comment by mknblch** [comment]
Only clustering based on modularity is implemented yet. Thats the first part of the louvain algorithm. I guess Gephi implements Louvain completly and therefore recreates a graph from the results of the first phase until no more iterations can be made. That would explain Gephis high iteration cound and low cluster count.

**Comment by mknblch** [comment]
i added an issue for Phase  2 in #96

**Comment by tomasonjo** [comment]
I misunderstood iterations for passes through Phase 1 and Phase 2 of Louvain.  There is no problem with iterations as of how they are implemented, i checked some small graphs where there is only one pass through needed and our results are ok.
Gephi implements Louvain completely so the number of community is smaller because of more passes.
As @mknblch already added this as feature request I wll close this ticket
