### ISSUE TITLE
Publish to Maven

### ISSUE THREAD

**Issue by eastlondoner** [neo4j-contrib/neo4j-graph-algorithms#426]
Are releases published to Maven? 

It would make it much easier for me to include this in my project if I could pull the jar automatically from maven.

**Comment by jexp** [comment]
It's not meant to be consumed from embedded as such.
So the releases are currently handled via GH Releases.

https://github.com/neo4j-contrib/neo4j-graph-algorithms/releases

But we can do maven central at some point going forward.

**Comment by eastlondoner** [comment]
maven != embedded 
I have an automated build for my plugins dir which collects various things from maven, builds a couple of things of my own and publishes them to my plugins dir

**Comment by jexp** [comment]
Right, I'll do the next releases to maven central too.

**Comment by eastlondoner** [comment]
@jexp you are a scholar and a gentleman

**Comment by szarnyasg** [comment]
Note: this project is deployed as the [`graph-algorithms-algo`](https://mvnrepository.com/artifact/org.neo4j/graph-algorithms-algo) package, not to be confused with [`neo4j-graph-algo`](https://mvnrepository.com/artifact/org.neo4j/neo4j-graph-algo) (which is the deployment of the `graph-algo` project of the core Neo4j repository).
