### ISSUE TITLE
Thread safe WeightMap

### ISSUE THREAD

**Issue by mknblch** [neo4j-contrib/neo4j-graph-algorithms#44]
The current WeightMap is not threadsafe for write access. Evaluate int->double / int->int backed mapping logic. To implement this we first need some kind of mapping between the long-relationship ids and their inner representation

**Comment by jexp** [comment]
We don't need the relationship id's.
For our purpose the source-node-id + target node-id should be good enough.

For both we have a long->int mapping. and then can do `source << 32 | target` -> weight
