### ISSUE TITLE
Closeness centrality on disconnected components

### ISSUE THREAD

**Issue by tomasonjo** [neo4j-contrib/neo4j-graph-algorithms#446]
As mentioned in https://github.com/neo4j-contrib/neo4j-graph-algorithms/issues/445 using same data,if we run closeness centrality on this network without filtering out disconnected components provides strange results. Only the largest wCC get its data normalized ? 

While the nodes that are in smaller wCCs with at least 2 members get really weird result. Our graph has 1 big component and 3 small ones with 9,7 and 2 members, total 18 excluding single nodes as components.  

Running the algorithm on only the largest wCC:
```
CALL algo.closeness.stream(
'MATCH (u:Hero) WHERE u.partition = 2 RETURN id(u) as id', 
'MATCH (u1:Hero)-[:KNOWS]-(u2:Hero) RETURN id(u1) as source,id(u2) as target',
{graph:'cypher'}) YIELD nodeId, centrality
WITH nodeId,centrality 
ORDER BY centrality DESC LIMIT 20
MATCH (h:Hero) where id(h)=nodeId
RETURN h.name as hero, centrality
```

Results:

![closeness-gephi](https://user-images.githubusercontent.com/19948365/32134596-6cc99f58-bbf0-11e7-89fa-c45cd38d01fd.png)

These results are totally same as in gephi.

If we run the algorithm without filtering only the largest wCC:

![gephi-mm](https://user-images.githubusercontent.com/19948365/32134625-2938c70e-bbf1-11e7-8b74-a51ceb1dbf2b.png)

So if you check first 18 nodes that are disconnected from main component get weird results, and the biggest component results are ok. This can be confusing for users

**Comment by mknblch** [comment]
I dont know how gephi implements CC. But as far as i know CC is only reliable on connected graph. Therefore we implemented hamonic centrality which doesn't suffer from disconnected graphs.
