### ISSUE TITLE
No output for `CALL algo.list()`

### ISSUE THREAD

**Issue by MartinSeeler** [neo4j-contrib/neo4j-graph-algorithms#458]
Calling `CALL algo.list()` in Cypher returns `(no changes, no records)`.
The same happens for `CALL algo.list() YIELD name`.
Although, calling `CALL dbms.procedures()` lists all procedures, including the algo.* procedures, as expected.

As seen in the code, the function calls internally
```
CALL dbms.procedures() 
YIELD name, signature, description 
WHERE name starts with 'algo.' AND name <> 'algo.list' 
RETURN name, signature, description ORDER BY name
```

When I execute the above statement as Cypher query in the browser, it does return the expected output with all algo procedures.

**Comment by jexp** [comment]
Actually the latest is:

```
CALL dbms.procedures()
YIELD name, signature, description
WHERE name starts with 'algo.' AND name <> 'algo.list' AND ($name IS NULL OR name CONTAINS $name)
RETURN name, signature, description ORDER BY name
```

which seems to have a problem with the defaultValue="null"

try `call algo.list("")` for the time being. I'll fix it.

**Comment by MartinSeeler** [comment]
Yes indeed, that works for me. Thanks!

**Comment by MartinSeeler** [comment]
Closed and fixed including test in 36 minutes, nice!

![](https://media.giphy.com/media/FFQegRpaJSRaw/giphy.gif)
