### ISSUE TITLE
LPA cypher loading

### ISSUE THREAD

**Issue by tomasonjo** [neo4j-contrib/neo4j-graph-algorithms#463]
There is some sort of a bug with LPA cypher loading:

Create Data: 

```
CREATE (nAlice:User {id:'Alice',predefined_label:52})
,(nBridget:User {id:'Bridget',predefined_label:21})
,(nCharles:User {id:'Charles',predefined_label:43})
,(nDoug:User {id:'Doug',predefined_label:21})
,(nMark:User {id:'Mark',predefined_label: 19})
,(nMichael:User {id:'Michael', predefined_label: 52})
CREATE (nAlice)-[:FOLLOW]->(nBridget)
,(nAlice)-[:FOLLOW]->(nCharles)
,(nMark)-[:FOLLOW]->(nDoug)
,(nBridget)-[:FOLLOW]->(nMichael)
,(nDoug)-[:FOLLOW]->(nMark)
,(nMichael)-[:FOLLOW]->(nAlice)
,(nAlice)-[:FOLLOW]->(nMichael)
,(nBridget)-[:FOLLOW]->(nAlice)
,(nMichael)-[:FOLLOW]->(nBridget)
,(nCharles)-[:FOLLOW]->(nDoug);
```

Run algo:

```
CALL algo.labelPropagation('MATCH (u:User) RETURN id(u) as id', 
'MATCH (u1:User)-[rel:FOLLOW]->(u2:User) 
RETURN id(u1) as source,id(u2) as target','BOTH', 
{iterations:10,partitionProperty:'partition', write:true,graph:"cypher"}) 
YIELD nodes

```

I get an error:

> Failed to invoke procedure `algo.labelPropagation`: Caused by: java.lang.IllegalArgumentException: No column "weight" exists

I've tried different direction settings and also `RETURN id(u1) as source,id(u2) as target,1 as weight` but the error persists

**Comment by knutwalker** [comment]
@tomasonjo our LPA uses weights from relationships as well as nodes, the `weight` missing here is for the nodes query (you probably have to do something similar with `partition` as well):

```
CALL algo.labelPropagation(
    'MATCH (u:User) RETURN id(u) as id, u.weight as weight', 
    'MATCH (u1:User)-[rel:FOLLOW]->(u2:User) RETURN id(u1) as source,id(u2) as target, rel.weight as weight',
…)
```

That's just a workaround, I suppose. What I'd like to have is to use the default weight if the cypher statements don't contain the respective properties.

**Comment by knutwalker** [comment]
I added #464 as a follow-up to track this.

**Comment by tomasonjo** [comment]
It also needs a column value ?

This works. results are ok.

```
CALL algo.labelPropagation(
    'MATCH (u:User) RETURN id(u) as id, 1 as weight, 1 as value', 
    'MATCH (u1:User)-[rel:FOLLOW]->(u2:User) RETURN id(u1) as source,id(u2) as target, rel.weight as weight','OUTGOING',{graph:"cypher",write:true,partitionProperty:"lpa1"}) YIELD nodes
```

**Comment by knutwalker** [comment]
You're right, `value` is the equivalent to the partitionKey setting.

**Comment by mneedham** [comment]
@tomasonjo default should work now via this commit - https://github.com/neo4j-contrib/neo4j-graph-algorithms/commit/7337e65062ba78c76e1cb6b7e50099c851e22fb5
