### ISSUE TITLE
Use defaults weights/property values in cypher loading

### ISSUE THREAD

**Issue by knutwalker** [neo4j-contrib/neo4j-graph-algorithms#464]
After implementing `cypher` for LPA, @tomasonjo found that the weight and value properties aren't optional: https://github.com/neo4j-contrib/neo4j-graph-algorithms/issues/463.

All other loaders use the default weight or default property value if a node or relationship doesn't have to configured one defined, whereas the cypher loaders fails. It should behave like the other loaders and use the default values in case the weight/value property wasn't even defined in the cypher statements.

**Comment by mneedham** [comment]
Fixed by: https://github.com/neo4j-contrib/neo4j-graph-algorithms/commit/7337e65062ba78c76e1cb6b7e50099c851e22fb5
