### ISSUE TITLE
Counting triangles

### ISSUE THREAD

**Issue by charlieabela** [neo4j-contrib/neo4j-graph-algorithms#473]
Hi
I'm using call algo.triangleCount.stream('User', 'FOLLOW') YIELD nodeId, triangles; on the graph used in the partitioning example and the result is the following:
╒════════╤═══════════╕
│"nodeId"│"triangles"│
╞════════╪═══════════╡
│26      │8          │
├────────┼───────────┤
│27      │8          │
├────────┼───────────┤
│28      │0          │
├────────┼───────────┤
│29      │0          │
├────────┼───────────┤
│31      │0          │
├────────┼───────────┤
│32      │8          │
└────────┴───────────┘
could not understand why there are 8 listed triangles. Is this a bug or maybe the algorithm can't handle multiple edges?

**Comment by tomasonjo** [comment]
Recreate data:

```
CREATE (nAlice:User {id:'Alice',predefined_label:52})
,(nBridget:User {id:'Bridget',predefined_label:21})
,(nCharles:User {id:'Charles',predefined_label:43})
,(nDoug:User {id:'Doug',predefined_label:21})
,(nMark:User {id:'Mark',predefined_label: 19})
,(nMichael:User {id:'Michael', predefined_label: 52})
CREATE (nAlice)-[:FOLLOW]->(nBridget)
,(nAlice)-[:FOLLOW]->(nCharles)
,(nMark)-[:FOLLOW]->(nDoug)
,(nBridget)-[:FOLLOW]->(nMichael)
,(nDoug)-[:FOLLOW]->(nMark)
,(nMichael)-[:FOLLOW]->(nAlice)
,(nAlice)-[:FOLLOW]->(nMichael)
,(nBridget)-[:FOLLOW]->(nAlice)
,(nMichael)-[:FOLLOW]->(nBridget)
,(nCharles)-[:FOLLOW]->(nDoug);
```
Check triangles:

```
CALL algo.triangle.stream('User','FOLLOW')
yield nodeA,nodeB,nodeC;
```

Results:

![re](https://user-images.githubusercontent.com/19948365/32741405-71402120-c8a6-11e7-8574-caf7c6e1c008.png)


I have played around a bit and found out the following:

All combinations of relationships that form a triangle are counted. In above example there are 8 different combinations of relationships that can be used to form a triangle. 

Example:

![as](https://user-images.githubusercontent.com/19948365/32741637-35e18a1e-c8a7-11e7-8d38-0afc5ab5c782.png)


Results:

![ss](https://user-images.githubusercontent.com/19948365/32741659-49c8cff6-c8a7-11e7-9624-44baf6b3f215.png)

Here we can observe, that there are 2 combinations of rels that can be used to form a triangle...

Maybe this is not ideal result. What would you expect to see as results @charlieabela ?

**Comment by jexp** [comment]
If we added an option to count each triangle only once, on which node would that be? Lowest Id?
@mknblch what do you think?

You could use the stream method, sort the 3 nodes by id and return distinct values.

Can you try this @tomasonjo and see what it returns.

```
CALL algo.triangle.stream('User','FOLLOW')
yield nodeA,nodeB,nodeC
RETURN distinct apoc.coll.sort([nodeA,nodeB,nodeC]) as triangle;
```

**Comment by mknblch** [comment]
@jexp we do restrict the algorithm on the condition: `id(A) < id(B) < id(C)` but since all triangle* algorithms treat the graph as **undirected** we iterate over (Michael) <-> (Bridget) twice. 

I created a testcase which illustrates the problem.

Based on the following graph i print all relationships.

```
CREATE (a:Node {id:'a'})
	 ,(b:Node {id:'b'})
	 ,(c:Node {id:'c'})
CREATE (a)-[:FOLLOW]->(b)
	 ,(a)-[:FOLLOW]->(c)
	 ,(b)-[:FOLLOW]->(c);

a -> c
a -> b
b -> a
b -> c
c -> b
c -> a  // everything fine
```

while the following graph leads unexpected results:

```
CREATE (a:Node {id:'a'})
	 ,(b:Node {id:'b'})
	 ,(c:Node {id:'c'})
CREATE (a)-[:FOLLOW]->(b)
	 ,(a)-[:FOLLOW]->(c)
	 ,(b)-[:FOLLOW]->(c)  <-- forward
	 ,(c)-[:FOLLOW]->(b);  <-- backward
	 
a -> c
a -> b
b -> c
b -> a
b -> c
c -> b  <-- twice
c -> a
c -> b  <-- twice
```
  
I think we ran into the same problem like before with weights.

**Comment by charlieabela** [comment]
Thanks for the clarifications.
The test case presented by Martin highlights the issue precisely. In the
case I presented in my previous message, every node a, b, c had multiple
edges (bi-directional) to each other. Yet the result still reported 8
triangles.
I tried
CREATE (a)-[:FOLLOW]->(b)
, (b)-[:FOLLOW]->(a)
     ,(a)-[:FOLLOW]->(c)
     ,(c)-[:FOLLOW]->(a)
     ,(b)-[:FOLLOW]->(c)
     ,(c)-[:FOLLOW]->(b);

and the result was

╒═══════╤═══════╤═══════╕
│"nodeA"│"nodeB"│"nodeC"│
╞═══════╪═══════╪═══════╡
│21     │22     │23     │
├───────┼───────┼───────┤
│21     │22     │23     │
├───────┼───────┼───────┤
│21     │22     │23     │
├───────┼───────┼───────┤
│21     │22     │23     │
├───────┼───────┼───────┤
│21     │22     │23     │
├───────┼───────┼───────┤
│21     │22     │23     │
├───────┼───────┼───────┤
│21     │22     │23     │
├───────┼───────┼───────┤
│21     │22     │23     │
└───────┴───────┴───────┘

so still 8 triangles are reported.

C

**Comment by mknblch** [comment]
We did some work on this problem (dont remember the exact commit). At least the Huge Graph now implements a logic which prevents oposite edges from beeing counted twice. It is not yet implemented in Heavy (default), Light or View. So you have to use `graph:'huge'` to enable it.
