### ISSUE TITLE
Iteration on undirected graphs

### ISSUE THREAD

**Issue by mknblch** [neo4j-contrib/neo4j-graph-algorithms#475]
In a graph where only one relationship between a pair of nodes exist everything is fine while the following graph leads to unexpected results when treating it as **undirected**

```
CREATE (a:Node {id:'a'})
	 ,(b:Node {id:'b'})
	 ,(c:Node {id:'c'})
CREATE (a)-[:FOLLOW]->(b)
	 ,(a)-[:FOLLOW]->(c)
	 ,(b)-[:FOLLOW]->(c)  <-- forward
	 ,(c)-[:FOLLOW]->(b);  <-- backward
	 
a -> c
a -> b
b -> c  <
b -> a
b -> c  <
c -> b  <
c -> a
c -> b  <
```

Did we ran into the same problem like before with weights? Seems like we have to clarify how to import such graphs

**Comment by jexp** [comment]
We have to document how the model mapping works

* neo graph -> graph model
* graph model -> algorithm

So we should have document  (and provide config & examples) how to load the different types of source graphs into an undirected model and a directed model

And then how to use these models with algorithms that expect undirected or directed graphs (+ optional direction as input)

**Comment by mknblch** [comment]
During import we allow only one connection between a pair of nodes per direction (in, out) in the directed case but two connections for `BOTH` the undirected case. This might be confusing and will probably lead to unexpected results in some algorithms. Another problem arises when we ask for the undirected degree of node B or C. Because we just add the count of In and Out relations we get 3 in this case which is clearly wrong

**Comment by mknblch** [comment]
The Problem with relationships in opposite directions between a pair of nodes has already been solved in the HugeGraph and gets currently implemented in Heavy. Im closing this issue therefore
