### ISSUE TITLE
Remove LightGraph in favor of HugeGraph

### ISSUE THREAD

**Issue by knutwalker** [neo4j-contrib/neo4j-graph-algorithms#499]
The encoding of LightGraph makes it nigh impossible to parallelize loading and is superseded by HugeGraph, that is, Huge is what a parallel capable Light would have to look like.

- Remove LightGraph from code, tests, benchmarks, and docs.
- Deprecate procedure API/config, i.e. don't fail when light is selected but default to heavy (huge?) and issue a warning

**Comment by mneedham** [comment]
LightGraph is remove via this commit - https://github.com/neo4j-contrib/neo4j-graph-algorithms/commit/bf4a7937d86dcb29a10dc5fd0bd15fd33674ebcd
