### ISSUE TITLE
Minimum Spanning Tree (mst) not running correctly

### ISSUE THREAD

**Issue by runshot1** [neo4j-contrib/neo4j-graph-algorithms#510]
Hello,

I got the same problems as in https://stackoverflow.com/questions/47673387/how-does-the-minimum-spanning-tree-in-neo4j-work
The result of the mst-Algorithm is even worse in my project: in average after some few nodes the tree building stops. I am using Neo4j 3.2.6 and Algo 3.2.5.2.
The shortestPath as example is working fine in my project (when u find out that the weight property has to be an integer number and not decimal, which is not documented)
So the weight Property for the mst is also an integer.

EDIT:
Updated to Versions: Neo4j 3.3.1 and Algo 3.3.0.0
The Results are actually better, but still the algorithm cant handle bigger graphs well (>50 nodes)

**Comment by mknblch** [comment]
pls check #511

**Comment by runshot1** [comment]
Hello,
thanks for fast answers. We tried the new algorithms with neo4j 3.3.1 and algo branch 3.3 (3.3.0.0), also with neo4j 3.2.8 and algo branch 3.2 (3.2.5.2)
With smaller graphs the new algorithms (mst, spanningTree) are successfull, but more complex/bigger graphs:
Failed to invoke procedure `algo.spanningTree`: Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
Also graph:huge doesn't help
Maybe we are doing something wrong with the versions, or there is still a bug

**Comment by mknblch** [comment]
Hi thanks for the info. You are not the first one with this problem although Ive never been able to reproduce this behaviour. Can you tell me the exact nodeCount of your graph and maybe the query youve been using.

**Comment by runshot1** [comment]
I could reproduce the graph, as small as possible. I got ArrayIndexOutOfBoundsException: 154.
Here you go (sorry for all the single queries):
Query: 
`MATCH (start:Point0) WHERE (start)-[:Line{used:'n'}]->() AND NOT (start)<-[:Line{used:'n'}]-() WITH ID(start) as id CALL algo.spanningTree.minimum('Point0', 'Line', 'length', id, {write:true, writeProperty:'mwst'}) YIELD loadMillis RETURN loadMillis;`

Graph:
`CREATE (n:Point0 {pointID:'600475.625_486802.1878'});
CREATE (n:Point0 {pointID:'601449.0001_487594.5312'});
MATCH (a:Point0),(b:Point0) WHERE a.pointID ='600475.625_486802.1878' AND b.pointID ='601449.0001_487594.5312' CREATE (a)-[r:Line {lineID:74898, length:1265, used:'n'}]->(b);
CREATE (n:Point0 {pointID:'600377.8125_486646.9686'});
MATCH (a:Point0),(b:Point0) WHERE a.pointID ='600475.625_486802.1878' AND b.pointID ='600377.8125_486646.9686' CREATE (a)-[r:Line {lineID:102531, length:184, used:'n'}]->(b);
CREATE (n:Point0 {pointID:'601026.9998_487032.3438'});
MATCH (a:Point0),(b:Point0) WHERE a.pointID ='600377.8125_486646.9686' AND b.pointID ='601026.9998_487032.3438' CREATE (a)-[r:Line {lineID:90253, length:759, used:'n'}]->(b);
CREATE (n:Point0 {pointID:'600714.8126_486560.6564'});
MATCH (a:Point0),(b:Point0) WHERE a.pointID ='601026.9998_487032.3438' AND b.pointID ='600714.8126_486560.6564' CREATE (a)-[r:Line {lineID:105579, length:580, used:'n'}]->(b);
CREATE (n:Point0 {pointID:'599716.3127_484906.4375'});
MATCH (a:Point0),(b:Point0) WHERE a.pointID ='600714.8126_486560.6564' AND b.pointID ='599716.3127_484906.4375' CREATE (a)-[r:Line {lineID:86248, length:1970, used:'n'}]->(b);
CREATE (n:Point0 {pointID:'599805.6251_485323.0938'});
MATCH (a:Point0),(b:Point0) WHERE a.pointID ='600714.8126_486560.6564' AND b.pointID ='599805.6251_485323.0938' CREATE (a)-[r:Line {lineID:120644, length:1586, used:'n'}]->(b);
CREATE (n:Point0 {pointID:'600052.7502_486069.0312'});
MATCH (a:Point0),(b:Point0) WHERE a.pointID ='599805.6251_485323.0938' AND b.pointID ='600052.7502_486069.0312' CREATE (a)-[r:Line {lineID:107178, length:810, used:'n'}]->(b);
CREATE (n:Point0 {pointID:'600087.2501_486219.75'});
MATCH (a:Point0),(b:Point0) WHERE a.pointID ='600052.7502_486069.0312' AND b.pointID ='600087.2501_486219.75' CREATE (a)-[r:Line {lineID:67908, length:156, used:'n'}]->(b);
CREATE (n:Point0 {pointID:'599711.4999_485361.2187'});
MATCH (a:Point0),(b:Point0) WHERE a.pointID ='600087.2501_486219.75' AND b.pointID ='599711.4999_485361.2187' CREATE (a)-[r:Line {lineID:88652, length:986, used:'n'}]->(b);
CREATE (n:Point0 {pointID:'600103.0_486262.6562'});
MATCH (a:Point0),(b:Point0) WHERE a.pointID ='600087.2501_486219.75' AND b.pointID ='600103.0_486262.6562' CREATE (a)-[r:Line {lineID:98716, length:45, used:'n'}]->(b);
CREATE (n:Point0 {pointID:'600177.6874_486784.9062'});
MATCH (a:Point0),(b:Point0) WHERE a.pointID ='600103.0_486262.6562' AND b.pointID ='600177.6874_486784.9062' CREATE (a)-[r:Line {lineID:107320, length:537, used:'n'}]->(b);
CREATE (n:Point0 {pointID:'600198.0624_486889.6562'});
MATCH (a:Point0),(b:Point0) WHERE a.pointID ='600177.6874_486784.9062' AND b.pointID ='600198.0624_486889.6562' CREATE (a)-[r:Line {lineID:91794, length:106, used:'n'}]->(b);
CREATE (n:Point0 {pointID:'599709.1877_486545.1874'});
MATCH (a:Point0),(b:Point0) WHERE a.pointID ='600198.0624_486889.6562' AND b.pointID ='599709.1877_486545.1874' CREATE (a)-[r:Line {lineID:87555, length:602, used:'n'}]->(b);
CREATE (n:Point0 {pointID:'599698.125_485287.6252'});
MATCH (a:Point0),(b:Point0) WHERE a.pointID ='600177.6874_486784.9062' AND b.pointID ='599698.125_485287.6252' CREATE (a)-[r:Line {lineID:122070, length:1643, used:'n'}]->(b);
MATCH (a:Point0),(b:Point0) WHERE a.pointID ='600103.0_486262.6562' AND b.pointID ='600377.8125_486646.9686' CREATE (a)-[r:Line {lineID:122071, length:474, used:'n'}]->(b);
MATCH (a:Point0),(b:Point0) WHERE a.pointID ='599711.4999_485361.2187' AND b.pointID ='600052.7502_486069.0312' CREATE (a)-[r:Line {lineID:107319, length:792, used:'n'}]->(b);`

**Comment by mknblch** [comment]
Totally forgot about this issue - sorry ;) Could you try to build the project by yourself and use that one instead of the prebuilt release?

**Comment by runshot1** [comment]
We built it by ourself with maven, else we would not be able to test the new methods, right? Did I understood that correctly?

**Comment by mknblch** [comment]
Exactly. Clone the repository and build it with maven and use the resulting jar.

**Comment by runshot1** [comment]
We did so ;) And the above behaviour started.

**Comment by mknblch** [comment]
That is strange. Im going to do some tests.

**Comment by mknblch** [comment]
I added an unitTest [branch](https://github.com/mknblch/neo4j-graph-algorithms/tree/debug_mst_510) for the issue and it works well. Im going to check what happens from within an running neo4j instance.

**Comment by mknblch** [comment]
I tried a fresh build of the current 3.2 branch on neo4j-community-3.2.8. Your example works well:

```
0 -> 1
0 -> 2
2 -> 10
2 -> 3
3 -> 4
4 -> 5
7 -> 9
7 -> 6
8 -> 7
10 -> 11
10 -> 8
11 -> 14
11 -> 12
12 -> 13
```

Im going to try it with another version tomorrow.

**Comment by mknblch** [comment]
I also tried your example with neo4j-community-3.3.1 without any problem. Sorry i cant reproduce your error.

**Comment by runshot1** [comment]
Hello, okay. So we tried again with algo 3.2 and 3.2.8. Still errors, but only sometimes. We tried a lot, restarting neo4j, browser/shell/python and different graphs. In the end, we have a 50/50 error chance. I made a file with a bigger example and good chance of error. It includes detach deleting, creating graph and trying the mst algorithm at the end. Just paste code in the cypher shell. Hope that we can reproduce the error for you, sometimes it is necessary to run the script multiple times without restarting neo4j.
[query.txt](https://github.com/neo4j-contrib/neo4j-graph-algorithms/files/1642964/query.txt)

**Comment by runshot1** [comment]
So right now we went for all and deleted our db folder and restarted neo4j. Then in the 3rd run the error appeard

**Comment by mknblch** [comment]
I ran your query in the shell (3.3.1 & 3.2.8) without any problems. Even repeatedly firing the last 4 queries did not trigger an exception. Instead i got the expected output:
```
neo4j-sh (?)$ MATCH (start:Point3) WHERE (start)-[:Line{used:'n'}]->() AND NOT (start)<-[:Line{used:'n'}]-() WITH ID(start) as id CALL algo.spanningTree.minimum('Point3', 'Line', 'length', id, {write:true, writeProperty:'mwst'}) YIELD loadMillis RETURN loadMillis;
+------------+
| loadMillis |
+------------+
| 1          |
| 1          |
| 3          |
+------------+
```

Could you pls check your `neo4j/logs/debug.log` for hints?

**Comment by mknblch** [comment]
Ok finaly i got the error. Repeatedly running the whole script did indeed trigger it

**Comment by mknblch** [comment]
We found the error. I added ticket #535 for this. The error happens in the HugeGraphLoader so Heavy and View should be fine. But Heavy nor View do not implement the `asUndirected(..)` method yet which might result in a wrong Tree. But you could give it a try using `{graph:'heavy'}` in the config map. Please be patient about this. The Undirected-Iface gets currently implemented in Heavy and the OOB issue is high priority.

**Comment by mknblch** [comment]
Bugfix is in #534

**Comment by runshot1** [comment]
The algorithm is indeed working fine now. Incredible performance boost while analysing our river networks, thanks for the quick fix
