### ISSUE TITLE
Louvain: Failed to invoke procedure `algo.louvain`: Caused by: java.lang.NoClassDefFoundError: org/neo4j/values/storable/Value

### ISSUE THREAD

**Issue by LittileFatNoRun** [neo4j-contrib/neo4j-graph-algorithms#512]
I use `CALL algo.louvain("Person","KNOW")`，but it return java.lang.NoClassDefFoundError: org/neo4j/values/storable/Value. Is that because my neo4j edition is 3.1.

**Comment by jexp** [comment]
Yes you need to use the right version for your db version
