### ISSUE TITLE
weight not considered in pagerank computing

### ISSUE THREAD

**Issue by liz282907** [neo4j-contrib/neo4j-graph-algorithms#514]
i run the following cypher loading on a directed graph and define the weight property of the relationship. however ,it seems that whether the 'weight' is defined doesn't change the result .

![image](https://user-images.githubusercontent.com/11833779/33869047-b5b4cdea-df41-11e7-8aec-7e20f030aeef.png)

**Comment by tomasonjo** [comment]
Pagerank does not support weight option.

**Comment by mneedham** [comment]
We have support for weights now - https://neo4j.com/docs/graph-algorithms/current/algorithms/page-rank/#algorithms-pagerank-weighted-sample
