### ISSUE TITLE
algo.unionFind can not group some relationship when use threshold

### ISSUE THREAD

**Issue by ghostHBL** [neo4j-contrib/neo4j-graph-algorithms#533]
I have node of "Person" and relationship of "KNOWS" in my graph, when I use 
CALL algo.unionFind("Person", "KNOWS", {threshold:0.40, defaultValue:0.0, write: true, partitionProperty:'partition', weightProperty:'weight'}) 
to find connected component there is some connected whose weight is 1 that can not group into a some partition, is there some issue when use threshold?

**Comment by mknblch** [comment]
So you have a Node `Person` which is connected to your Graph with relationship `KNOWS` and has a weightProperty called `weight` which is 1.0 but it does not belong to the set where it should be. Is this right? I just tried this setup without an error. Can you create a cypher query to reproduce the error pls?

**Comment by ghostHBL** [comment]
I found that when I use 
CALL algo.unionFind("MATCH (n:Person) RETURN id(n) as id",
"MATCH (a:Person)-[r:KNOWS]->(b:Person) WHERE r.risk_score>0.4 RETURN id(a) as source, id(b) as target",
{graph:'cypher',write:true, partitionProperty:'cc_id'})
to get connected component , it work well.

My graph is too large, I don't know how to create a cypher query for you to reproduce the error. And I try to reproduce it in a small graph but the error didn't come.

Any suggestion to debug this error?

**Comment by mknblch** [comment]
if `risk_score` is the name of your weight-property the query should have been: 
`CALL algo.unionFind("Person", "KNOWS", {threshold:0.40, defaultValue:0.0, write: true, partitionProperty:'partition', weightProperty:'risk_score'})`

**Comment by ghostHBL** [comment]
Oh, I am sorry that I change the weightProperty from weight to risk_score, but they are same. the issue still come, not matter what weightProperty is used.

**Comment by mknblch** [comment]
Can you replicate this bug somehow? Or can you give me some more information about your dataset, its structure (maybe disconnected graph or so) and size? Ive never seen this bug so far.

**Comment by mknblch** [comment]
Please feel free to create a new issue/ reopen this one if the problem persists.
