### ISSUE TITLE
Change return type of HugeDegrees#degree

### ISSUE THREAD

**Issue by mknblch** [neo4j-contrib/neo4j-graph-algorithms#538]
The return type of HugeDegrees#degree(..) is still **int** but its possible to have nodes with more then 2b nodes which would break the impl.

**Comment by knutwalker** [comment]
The [Neo4j kernel api](https://github.com/neo4j/neo4j/blob/d5e31e3b02cbbe69106386a761f011ad5cd93b63/community/kernel/src/main/java/org/neo4j/kernel/api/ReadOperations.java#L173-L175) returns an `int` as well, that's why I used `int` for `HugeDegrees` as well.

**Comment by mknblch** [comment]
Force majeure
