### ISSUE TITLE
Programmatic compatibility matrix 

### ISSUE THREAD

**Issue by benbc** [neo4j-contrib/neo4j-graph-algorithms#539]
Please could you publish a compatibility matrix like the one for APOC [here](https://neo4j-contrib.github.io/neo4j-apoc-procedures/versions.json)?

This can be used to allow completely automated upgrades of Neo4j instances where the graph algos library is deployed..

**Comment by jexp** [comment]
We can use a similar gradle script like in apoc on the master branch.

Only that it has to grab the neo4j version from the pom and not build.gradle.

**Comment by jexp** [comment]
Perhaps we could use the same to check out a shallow version of the repo and build the docs, although we need the procedure list for that, which we could also generate using the algo jar and cypher.

**Comment by jexp** [comment]
@benbc please check: https://neo4j-contrib.github.io/neo4j-graph-algorithms/versions.json

Note I named the library's version: `version` not `algos` or such to make your parser more generic.

**Comment by benbc** [comment]
Thank you, Michael, that looks great.

**Comment by benbc** [comment]
@jexp It seems that the download URLs are wrong. For 3.3.0.0 the link in the matrix is https://github.com/neo4j-contrib/neo4j-graph-algorithms/releases/download/3.3.0.0/algos-3.3.0.0-all.jar. That returns a 404. But the releases page on Github give https://github.com/neo4j-contrib/neo4j-graph-algorithms/releases/download/3.3.0.0/graph-algorithms-algo-3.3.0.0.jar (which works).

**Comment by mneedham** [comment]
Think this is sorted now. Also have it wired up in CI so we can update it with a run of a build.
