### ISSUE TITLE
Directed closeness centrality

### ISSUE THREAD

**Issue by tomasonjo** [neo4j-contrib/neo4j-graph-algorithms#547]
I wanted to try out @mneedham statement.

> The Closeness Centrality algorithm is very sensitive to a single large distance or missing relationship - the closeness centrality for a node is 0 if there is just one other node it can't reach.
> If there's one node that no other nodes can reach then every node will have a closeness centrality of 0.

Create graph:
```
CREATE (alice:Person{id:"Alice"}),
       (michael:Person{id:"Michael"}),
       (karin:Person{id:"Karin"}),
       (chris:Person{id:"Chris"}),
       (will:Person{id:"Will"}),
       (mark:Person{id:"Mark"})
CREATE (michael)<-[:KNOWS]-(karin),
       (michael)-[:KNOWS]->(chris),
       (will)-[:KNOWS]->(michael),
       (mark)<-[:KNOWS]-(michael),
       (mark)-[:KNOWS]->(will),
       (alice)-[:KNOWS]->(michael),
       (will)-[:KNOWS]->(chris),
       (chris)-[:KNOWS]->(karin);
```

![directed](https://user-images.githubusercontent.com/19948365/35481713-6ba2e3ce-0429-11e8-87d0-e6b267c8d784.png)

All nodes are reachable between each other except that other nodes cannot reach Alice

run closeness:

```
CALL algo.closeness.stream('Person', 'KNOWS') YIELD nodeId, centrality
RETURN nodeId,centrality order by centrality desc limit 20;
```

Results:

n.id | centrality
-- | --
"Michael" | 0.7142857142857143
"Chris" | 0.625
"Mark" | 0.5
"Karin" | 0.45454545454545453
"Will" | 0.38461538461538464
"Alice" | 0

Our algorithm actually return 0 for a node that can reach all others but cannot be reached by others.

**Comment by mknblch** [comment]
I added a [unit test](https://github.com/mknblch/neo4j-graph-algorithms/blob/debug_546/tests/src/test/java/org/neo4j/graphalgo/algo/ClosenessCentralityIntegrationTest_546.java) using the HugeGraph and its deduplication logic. These are the results:

n.id | centrality
--|--
Alice | 0,556
Michael | 1,000
Karin | 0,625
Chris | 0,714
Will | 0,714
Mark | 0,625

**Comment by mneedham** [comment]
@tomasonjo it's even not displaying this behaviour if 'Alice's is in a different component:

```
CREATE (alice:Person{id:"Alice"}),
       (michael:Person{id:"Michael"}),
       (karin:Person{id:"Karin"}),
       (chris:Person{id:"Chris"}),
       (will:Person{id:"Will"}),
       (mark:Person{id:"Mark"})
CREATE (michael)<-[:KNOWS]-(karin),
       (michael)-[:KNOWS]->(chris),
       (will)-[:KNOWS]->(michael),
       (mark)<-[:KNOWS]-(michael),
       (mark)-[:KNOWS]->(will),
       (will)-[:KNOWS]->(chris),
       (chris)-[:KNOWS]->(karin);
```

```
CALL algo.closeness.stream('Person', 'KNOWS') YIELD nodeId, centrality
match (n:Person) WHERE id(n) = nodeId
RETURN n.id,centrality 
order by centrality desc limit 20;

╒═════════╤══════════════════╕
│"n.id"   │"centrality"      │
╞═════════╪══════════════════╡
│"Michael"│0.8333333333333334│
├─────────┼──────────────────┤
│"Chris"  │0.8333333333333334│
├─────────┼──────────────────┤
│"Karin"  │0.625             │
├─────────┼──────────────────┤
│"Mark"   │0.625             │
├─────────┼──────────────────┤
│"Will"   │0.5               │
├─────────┼──────────────────┤
│"Alice"  │0                 │
└─────────┴──────────────────┘
```

**Comment by mneedham** [comment]
Just for fun I tried out this same graph using the Python networkx library:

```
import networkx as nx

G = nx.Graph()

G.add_node("Alice")

relationships = [
    ("Karin", "Michael"),
    ("Michael", "Chris"),
    ("Will", "Michael"),
    ("Michael", "Mark"),
    ("Mark", "Will"),
    ("Will", "Chris"),
    ("Chris", "Karin"),
]

G.add_edges_from(relationships)

nx.closeness_centrality(G)
```

```
{'Alice': 0.0, 'Karin': 0.5333333333333333, 'Michael': 0.8, 'Chris': 0.6400000000000001, 'Will': 0.6400000000000001, 'Mark': 0.5333333333333333}
```

So that's even has different values as well. 

If I do it where Alice knows Michael it gives these results:

```
G = nx.Graph()

relationships = [
    ("Karin", "Michael"),
    ("Michael", "Chris"),
    ("Will", "Michael"),
    ("Michael", "Mark"),
    ("Mark", "Will"),
    ("Will", "Chris"),
    ("Chris", "Karin"),
    ("Alice", "Michael")
]

G.add_edges_from(relationships)

nx.closeness_centrality(G)
```

```
{'Karin': 0.625, 'Michael': 1.0, 'Chris': 0.7142857142857143, 'Will': 0.7142857142857143, 'Mark': 0.625, 'Alice': 0.5555555555555556}
```

**Comment by tomasonjo** [comment]
after some search i found this article talking about centrality in directed networks or how they call it prestige:

http://mrvar.fdv.uni-lj.si/sola/info4/uvod/part4.pdf -> page 6

talking about closeness centrality:

> If network is not strongly connected, we take only reachable vertices into account, but we weight the result with number of reachable vertices.

**Comment by mneedham** [comment]
@tomasonjo I put another node into the smaller connected component and now I'm really confused by the output!

```
CREATE (alice:Person{id:"Alice"}),
       (michael:Person{id:"Michael"}),
       (karin:Person{id:"Karin"}),
       (chris:Person{id:"Chris"}),
       (will:Person{id:"Will"}),
       (mark:Person{id:"Mark"}),
       (dave:Person{id:"Dave"})
CREATE 
	   (michael)<-[:KNOWS]-(karin),
       (michael)-[:KNOWS]->(chris),
       (will)-[:KNOWS]->(michael),
       (mark)<-[:KNOWS]-(michael),
       (mark)-[:KNOWS]->(will),
       (alice)-[:KNOWS]->(dave),
       (will)-[:KNOWS]->(chris),
       (chris)-[:KNOWS]->(karin),
       
       (michael)-[:KNOWS]->(karin),
       (michael)<-[:KNOWS]-(chris),
       (will)<-[:KNOWS]-(michael),
       (mark)-[:KNOWS]->(michael),
       (mark)<-[:KNOWS]-(will),
       (alice)<-[:KNOWS]-(dave),
       (will)<-[:KNOWS]-(chris),
       (chris)<-[:KNOWS]-(karin);
```

```
CALL algo.closeness.stream('Person', 'KNOWS') YIELD nodeId, centrality
match (n:Person) WHERE id(n) = nodeId
RETURN n.id,centrality 
order by centrality desc limit 20;

╒═════════╤════════════╕
│"n.id"   │"centrality"│
╞═════════╪════════════╡
│"Alice"  │6           │
├─────────┼────────────┤
│"Dave"   │6           │
├─────────┼────────────┤
│"Michael"│1.5         │
├─────────┼────────────┤
│"Chris"  │1.2         │
├─────────┼────────────┤
│"Will"   │1.2         │
├─────────┼────────────┤
│"Karin"  │1           │
├─────────┼────────────┤
│"Mark"   │1           │
└─────────┴────────────┘
```

How do Alice and Dave get scores of 6?!

![2018-01-30_20-56-29](https://user-images.githubusercontent.com/13220/35590874-0f01e8ee-0600-11e8-92fe-0985301d9ed5.png)

**Comment by tomasonjo** [comment]
I have noticed this behaviour in https://github.com/neo4j-contrib/neo4j-graph-algorithms/issues/546, I guess we have again two options how to solve this.

First one, could be frustrating for the user:

```
The Closeness Centrality algorithm is very sensitive to a single large distance or missing relationship - the closeness centrality for a node is 0 if there is just one other node it can't reach.
If there's one node that no other nodes can reach then every node will have a closeness centrality of 0.
```

Second option is to run algorithm treating each connected component as a separate graph, so Alice and David would have closeness centrality 1. This would mean following the logic from http://mrvar.fdv.uni-lj.si/sola/info4/uvod/part4.pdf

Above can solve undirected closeness. In a directed network we will almost always deal with unreachable nodes, so first option is not really an option, but the second option might also have its flaws in a less connected network.

**Comment by mneedham** [comment]
This is what networkx returns for the undirected 2 connected component graph from above:

```
# 2 connected components

G = nx.Graph()

relationships = [
    ("Karin", "Michael"),
    ("Michael", "Chris"),
    ("Will", "Michael"),
    ("Michael", "Mark"),
    ("Mark", "Will"),
    ("Alice", "Dave"),
    ("Will", "Chris"),
    ("Chris", "Karin")
]

G.add_edges_from(relationships)

sorted(nx.closeness_centrality(G).items(), key=lambda x: x[1] *-1)

[('Michael', 0.6666666666666666), ('Chris', 0.5333333333333333), ('Will', 0.5333333333333333), ('Karin', 0.4444444444444444), ('Mark', 0.4444444444444444), ('Alice', 0.16666666666666666), ('Dave', 0.16666666666666666)]
```

Interestingly the score it gives to Dave and Alice is 1/6, which is score / (#nodes - 1). I'm gonna debug our code a bit to see how it came up with the score of 6.

**Comment by mneedham** [comment]
Ok I see how we get the 6. The calculation is:

`nodes -1 / farness` and it's considering the farness of 'Dave' and 'Alice' to be a total of 1 when you could argue that it's actually infinity since they can't reach 'Michael', 'Mark', 'Chris', 'Karin', or 'Will'

**Comment by tomasonjo** [comment]
closed with https://github.com/neo4j-contrib/neo4j-graph-algorithms/issues/554
