### ISSUE TITLE
LIGHT cannot be resolved or is not a field

### ISSUE THREAD

**Issue by smadurange** [neo4j-contrib/neo4j-graph-algorithms#552]
Hi guys, I cloned the project and am working on branch 3.2. In Eclipse, I get the error `LIGHT cannot be resolved or is not a field` in the project `graph-algorithms-benchmark` in the file `UFBenchmarkCombination.java`. Offending lines are:

```
LIGHT_QUEUE(GraphImpl.LIGHT, UnionFindAlgo.QUEUE),
LIGHT_FORK_JOIN(GraphImpl.LIGHT, UnionFindAlgo.FORK_JOIN),
LIGHT_FJ_MERGE(GraphImpl.LIGHT, UnionFindAlgo.FJ_MERGE),
LIGHT_SEQ(GraphImpl.LIGHT, UnionFindAlgo.SEQ),
```

I can't actually find the implmentations for `GraphImpl.LIGHT` either. Please help. Thanks.

**Comment by mknblch** [comment]
We removed the LightGraph impl. a while ago. Seems like someone forgot to adapt the benchmarks. First of all just remove the invalid lines or deactivate the benchmark-profile in maven. Im going to adapt the benchmarks real quick
