### ISSUE TITLE
How to access custom properties of a Node?

### ISSUE THREAD

**Issue by smadurange** [neo4j-contrib/neo4j-graph-algorithms#556]
Hi,

I'm trying to access neo4j `Node` objects in a class like `org.neo4j.graphalgo.impl.ShortestPathDijkstra`.  The purpose of this is to access custom attributes of nodes in an algorithm such as`longitude` and `latitude` of a node.

What is the best way to access custom properties from a node such as this? Thank you.

**Comment by smadurange** [comment]
Hi guys, any update on this? Thanks.

**Comment by mknblch** [comment]
Hi. 

The best way would be to load the related data in the import process and access them with `NodeProperties` and `RelationshipWeights` interface. 

But our API does only support **one** property at nodes and relations at the moment. We are currently thinking about some kind of mapping but until this gets implemented you have to use the neo4j core api to access your stuff. 

In your procedure you could just pass the `GraphDatabaseAPI` directly into your Algorithm along with the Graph iface. When you traverse the graph using the graph-algo-api you get a mapped nodeId. You can easily transform them back into its neo4j-id (`graph.toOriginalNodeId(..)`) and use the core api to query your data. 

This might not be the most efficient way but should work for now.

**Comment by smadurange** [comment]
Thanks for the advice. Closing this now.
