### ISSUE TITLE
UnionFind - export to graph

### ISSUE THREAD

**Issue by mneedham** [neo4j-contrib/neo4j-graph-algorithms#559]
[From Michael's experiments on mattis]

Writing the clusters back on dbpedia takes forever 85s vs. page-rank 20s and grows slower 133 s in the 2nd run

**Comment by mknblch** [comment]
UnionFind and PageRank can not be compared. UnionFind does a recursive traversion over the parent array to retrieve the cluster-id per node while PR just reads a value.
