### ISSUE TITLE
Calculate betweenness centrality for a single node only

### ISSUE THREAD

**Issue by Shiutang-Li** [neo4j-contrib/neo4j-graph-algorithms#562]
Hi:

I quickly went thru all the past issues and didn't find similar posts. I'm wondering if it's possible to calculate for betweenness centrality only for the node I'm interested, cuz it's not computationally efficient to calculate everything in the network and then use some matching node property to retrieve what I need (Especially when I have tons of sub-networks and for each sub-network I only need the betweenness centrality for only one or two nodes). Appreciate it a lot if there's any solution to this.

**Comment by mknblch** [comment]
I doubt this can be done with Brandes BC. To calculate only the betweenness centrality of one node you need the number of shortest paths from any pair of nodes and the number of passes through the node which is still `O(|V|^3)`

**Comment by Shiutang-Li** [comment]
I see. I'm simply wondering if there're more efficient ways if we only need partial information. Thanks for these thoughts.

**Comment by mknblch** [comment]
As usual, if you find an algorithm which suits your problem better and has not yet been implemented create a new issue and link us a paper.
