### ISSUE TITLE
A* Search for shortest path: community contributions

### ISSUE THREAD

**Issue by smadurange** [neo4j-contrib/neo4j-graph-algorithms#564]
Hi,

We have extended your dijkstra shortest path algorithm by implementing a* search. We found it to be 2 orders of magnitude faster at 8000 node graph. We would like to contribute back and send a pull request. Can you let us know whether you guys consider community contributions and if yes, how we go about it? Thanks.

**Comment by smadurange** [comment]
Great, will send a pull request against 3.3. Thanks.

**Comment by mneedham** [comment]
@smadurange if it's not too much hassle could you put it against 3.2 and then I'll forward merge it into 3.3 as well?

**Comment by smadurange** [comment]
@mneedham sure, no problem.
