### ISSUE TITLE
SSSP returns incorrect result

### ISSUE THREAD

**Issue by szarnyasg** [neo4j-contrib/neo4j-graph-algorithms#599]
I am working to implement the [LDBC Graphalytics](http://graphalytics.org/site/dist/index.html) workload using the Graph algorithms library.

I ran into an issue with SSSP. When looking for the shortest path between vertices 1 and 4, the algorithm finds the path with a cost of 5 (1->4), instead of the path with a cost of 4 (1->2->4->6->3->4).

The Cypher commands are as follows:

```
CREATE
  (v1:Node {VID: 1}),
  (v2:Node {VID: 2}),
  (v3:Node {VID: 3}),
  (v4:Node {VID: 4}),
  (v5:Node {VID: 5}),
  (v6:Node {VID: 6}),
  (v7:Node {VID: 7}) 
  ,(v1)-[:EDGE {WEIGHT: 0.5}]->(v2)
  ,(v1)-[:EDGE {WEIGHT: 5.0}]->(v3)
  ,(v2)-[:EDGE {WEIGHT: 0.5}]->(v5)
  ,(v3)-[:EDGE {WEIGHT: 2.0}]->(v4)
  ,(v5)-[:EDGE {WEIGHT: 0.5}]->(v6)
  ,(v6)-[:EDGE {WEIGHT: 0.5}]->(v3)
  ,(v6)-[:EDGE {WEIGHT: 4.0}]->(v7)
  ,(v1)-[:EDGE {WEIGHT: 5.0}]->(v4)
```

```
MATCH (startNode {VID: 1}), (endNode {VID: 4})
CALL algo.shortestPath(startNode, endNode, 'WEIGHT', {direction: 'OUTGOING'})
YIELD nodeCount, totalCost, loadMillis, evalMillis, writeMillis
RETURN totalCost
```

![image](https://user-images.githubusercontent.com/1402801/38740832-ca16baf8-3f38-11e8-9fa2-6de1ff639994.png)

The issue is not trivial to reproduce, however, I believe, my [example project](https://github.com/szarnyasg/sssp-issue) manages to consistently reproduce the issue.

* Removing the 6->7 edge (which has a weight of 23 and has nothing to do with either of the paths) resolves the issue, see https://github.com/szarnyasg/sssp-issue/blob/949cc8e8ed9772fb23029bc9a1e9fa2b21139aa0/src/main/java/sssp/SsspMain.java#L31
* Changing the order of the edge insertions can also resolve the issue.
* I tried running these queries repeatedly in a Neo4j server. First, I used the following approach: 1) delete all nodes in the database 2) insert the data 3) invoke the SSSP procedure again. This failed to reproduce the issue consistently. So I changed my approach: 1) stop the database, delete the database directory, restart the database 2) etc. This managed to reproduce the issue consistently, which might give a hint on the nature of the problem (maybe it has something to do with internal edge ids?).

**Comment by knutwalker** [comment]
Thanks for creating the issue, this is an interesting one.

The reason that it sometimes works is due to the order in which we read from the relationship store, which changes if you have a database with deletions or additional relationships.
I've detailed the reasons in #600. I've added your provided test cases and could reproduce this as well; the tests pass with #600.
