### ISSUE TITLE
Louvain detection result in different community structures with the same initial condition against  saying in LPA

### ISSUE THREAD

**Issue by bluelovecute** [neo4j-contrib/neo4j-graph-algorithms#608]
###
Community detection: Label Propagation
Constraints / when not to use it
In contrast with other algorithms label propagation can result in different community structures from the same initial condition.
###
The Louvain detection  can result different community structures with the same initial condition like LPA?

**Comment by mknblch** [comment]
The algorithm starts several computations at once (one per thread) and takes their best result for the next run. This can lead to different results per run. Currently we have no option to deactivate this behaviour but we could implement it if this is a problem.

**Comment by bluelovecute** [comment]
Thank you ，I just want to say that  it can  make some confuse  as saying in the doc #Neo4j Graph Algorithms User Guide#  that lpa in contrast with other algo（ result in different community structures from the same initial condition） ,  but  in fact , not  in contrast  with louvain  algo.

**Comment by bluelovecute** [comment]
Certainly, if louvain  have option to deactivate the behaviour will much better
