### ISSUE TITLE
Call to algo.shortestPath results in IllegalArgumentException

### ISSUE THREAD

**Issue by tbys** [neo4j-contrib/neo4j-graph-algorithms#649]
When I do the following query ...

```
MATCH (start), (end) WHERE ID(start) = 1 and ID(end) = 60000
CALL algo.shortestPath(start, end, 'cost')
YIELD nodeCount, totalCost
RETURN nodeCount, totalCost
```

Then I get the following error:

```
Neo.ClientError.Procedure.ProcedureCallFailed: Failed to invoke procedure `algo.shortestPath`: Caused by: java.lang.IllegalArgumentException: Unsupported type [TEXT] of value String("1"). Please use a numeric property.
```

I don't understand this error, as the arguments I pass to shortestPath should be a node, a node and the string 'cost'.

Is this a bug or am I missing something?

**Comment by tomasonjo** [comment]
Do you have the cost property stored as a number ( int or float)?

**Comment by tbys** [comment]
@tomasonjo 
> Do you have the cost property stored as a number ( int or float)?
Ah! It thought so, but re-examining my data creation script, it has a bug that turns all property values into strings. I'll change the script and recheck.

On a side note, the error message is a bit misleading in this case as it give the impression that the arguments given to the procedure were of the wrong type...

**Comment by tbys** [comment]
Ok, after updating the cost properties so that they are now numbers, the error no longer occurs.

Thanks!

(shortest path fails because of java.lang.OutOfMemoryError instead...grumble)

**Comment by mneedham** [comment]
@tbys I've just been trying to reproduce this locally and for some reason even if I set the properties as strings I can't get it to throw an error. Do you have a small sample dataset where you can reproduce every time that you could share so I can improve the error message?

**Comment by knutwalker** [comment]
@mneedham On 3.3 and earlier we used to get plain Objects from the kernel API and were parsing strings (https://github.com/neo4j-contrib/neo4j-graph-algorithms/blob/11d5101fbc603ba6cb05953ddc00c2982a016251/core/src/main/java/org/neo4j/graphalgo/core/utils/RawValues.java#L86-L91)

With 3.4 that changed to only support NumericValues: https://github.com/neo4j-contrib/neo4j-graph-algorithms/blob/933d2b1c1ed15d0c0f6ce57cff2323305108270e/core/src/main/java/org/neo4j/graphalgo/core/loading/ReadHelper.java#L81-L86

We could also add parsing to the 3.4 tree but I would err on the side of not doing "magic" parsing and continue to fail on non-numeric properties, as it might help to identify bugs (as it did here). In any case, we can probably improve the error message to make it more clear what is happening.
