### ISSUE TITLE
implement efficient random walks

### ISSUE THREAD

**Issue by jexp** [neo4j-contrib/neo4j-graph-algorithms#653]
Add methods to graph interface (Relationship) to access relationships by index

`void forRelationship(int nodeId, int index, RelationshipConsumer consumer);`

To allow an efficient implementation of random walk that is not O(n) for relationship selection but O(1) as we internally already store relationships in arrays.

Where `index = rand()*degree`.

Optionally think about batching and concurrent operations that walk multiple nodes at the same time.
Perhaps matrix ops are also interesting.

And consider "random walk with restart" paper: 

* http://www.cs.cmu.edu/~christos/PUBLICATIONS/icdm06-rwr.pdf
* http://www.zora.uzh.ch/id/eprint/111243/1/TR_WWW.pdf

**Comment by mneedham** [comment]
This one is done now.
