### ISSUE TITLE
Change Consumer into Functions to allow premature termination

### ISSUE THREAD

**Issue by mknblch** [neo4j-contrib/neo4j-graph-algorithms#68]
Since we might decide to get rid of the Iterator-methods (in #29) we should add the possibility to terminate the iteration within a forEach(..) method before all values have been emitted. This could be implemented by changing the Consumer into Functions which return a Boolean that either stops or continues the current iteration.

**Comment by jexp** [comment]
Yes BooleanFunction (i.e. Prediate).

**Comment by mknblch** [comment]
`org.neo4j.graphalgo.api.RelationshipConsumer` has already been changed in 3.1. `org.neo4j.graphalgo.api.NodeIterator` still needs to be done.
