### ISSUE TITLE
Using multiple node types for Louvain?

### ISSUE THREAD

**Issue by fraserh** [neo4j-contrib/neo4j-graph-algorithms#680]
I have Users who `FOLLOW` other Users, and this works well with the Louvain algo. Users can also `LIKE` Tags ('photography', 'travel' etc) and the Tags are very well connected. Is there any way to use the tags in the louvain calculation as well? Perhaps through a cypher weight calculation?

Any hints would be greatly appreciated :)

**Comment by renmjie** [comment]
CALL algo.louvain.stream(
  'MATCH (p) where labels(p) in [["U2"],["User"]]  RETURN id(p) as id',
  'MATCH (p1)-[*]-(p2) where all (edge in relationships(p) where  type(edge) in ["FR2"] )
   RETURN id(p1) as source, id(p2) as target ',
  {graph:'cypher',write:true});   I write cql like this, nodes include U2 and User; rel only incluse FR2.  You can try

**Comment by HashRocketSyntax** [comment]
Multiple labels:
```
MATCH (n)
WHERE n:Car OR n:Person
RETURN n
```
