### ISSUE TITLE
Implementing ArticleRank as an alternative algorithm to PageRank 

### ISSUE THREAD

**Issue by timholds** [neo4j-contrib/neo4j-graph-algorithms#689]
Hi, there is a popular alternative to PageRank called ArticleRank that I would like to implement. In short, it reduces the bias that PageRank has towards giving higher scores to nodes that get links from nodes that give out few links. This is useful in contexts like citation analysis of academic papers. The original paper can be seen here: https://sci-hub.tw/https://www.emeraldinsight.com/doi/abs/10.1108/00012530911005544

Specifically, to find the score for a given node, PageRank counts up all the incoming scores and divides them by the number of outgoing links for each given incoming page. ArticleRank assigns a score by counting up all the incoming scores divides, and divides them by the average number of outgoing links plus the number of outgoing links for each given incoming page. 

The PageRank equation:
![pagerank](https://user-images.githubusercontent.com/24782018/45064604-a3258580-b069-11e8-8290-07c5a192f828.png)

The ArticleRank equation:
![screenshot 2018-09-04 17 45 10](https://user-images.githubusercontent.com/24782018/45064753-5c845b00-b06a-11e8-8893-cc559c1cfd19.png)

From what I can tell, the process of implementing this algorithm would look like the following:
[ ] Implement as java class
[ ] Tests
[ ] Simple benchmark
[ ] Implement procedure
[ ] Benchmark on bigger graphs
[ ] Evaluation

Since I would be altering the already parallelized PageRank algorithm, I didn't add parallelization as an explicit step.

**Comment by mneedham** [comment]
Hi @timholds,

Sorry for the late reply - I didn't spot this issue until just now. 

I think we should be able to reuse most of the PageRank code that's already there given that the change is only to the equation. 

This is the part of the code where the calculation is done:

https://github.com/neo4j-contrib/neo4j-graph-algorithms/blob/3.4/algo/src/main/java/org/neo4j/graphalgo/impl/PageRank.java#L462

Let me know if you want to chat on Skype/Hangouts to figure out the best way to implement it.

Cheers, Mark

**Comment by timholds** [comment]
Hi @mneedham,

Thanks for getting back to me.

As of right now, the plan is to make a copy of PageRank.java, calling it ArticleRank.java and changing the singleIteration method that you have linked to above. 

I believe I will also need to make an ArticleRankProc.java that mirrors PageRankProc.java, and this is where I've gotten held up. So, if you do have some time, I would be happy to Skype or do a Hangout.

Thanks, Tim

**Comment by mneedham** [comment]
Hi @timholds,

Could you send me an email - mark.needham@neo4j.com - and then we can arrange Skype/Hangout.

Cheers, Mark
