### ISSUE TITLE
Similar Louvain query giving different results

### ISSUE THREAD

**Issue by aforadi** [neo4j-contrib/neo4j-graph-algorithms#700]
Hello,

I am calling Louvain algorithms using 2 different syntactical ways but the same meaning (alteast I think so :) ). I am getting different results and I don't understand if this is a bug.

1-
CALL algo.louvain(
         "MATCH (p:Network_L1_Louvain) RETURN  id(p) as id",
         "MATCH (p:Network_L1_Louvain)-[f:INTERACTED]-(m:Network_L1_Louvain) RETURN id(p) as source, id(m) as target",
         {graph:'cypher',write:true, writeProperty:'partition_test', concurrency:1});
2-
CALL algo.louvain('Network_L1_Louvain','INTERACTED',{concurrency:1, write:true,writeProperty:'partition_test2'});

2 results
+---------------------------------------------------------------------------------+
| loadMillis | computeMillis | writeMillis | nodes  | iterations | communityCount |
+---------------------------------------------------------------------------------+
| 5770       | 4501          | 4048        | 900558 | 5          | 100340         |
+---------------------------------------------------------------------------------+

1 results
| loadMillis | computeMillis | writeMillis | nodes  | iterations | communityCount |
+---------------------------------------------------------------------------------+
| 36892      | 1924257       | 2607        | 900558 | 5          | 83023          |
+---------------------------------------------------------------------------------+

The run times are also very different. Is this a known bug?

Thanks
Aditya

**Comment by aforadi** [comment]
2 more issues. 

a) It doesn't seem to make a difference if I use a weight property in #1.
#3
CALL algo.louvain(
         "MATCH (p:Network_L1_Louvain) RETURN  id(p) as id",
         "MATCH (p:Network_L1_Louvain)-[f:INTERACTED]-(m:Network_L1_Louvain) RETURN id(p) as source, id(m) as target, f.amt as weight",
         {graph:'cypher',write:true, writeProperty:'partition_L1', concurrency:1, weightProperty:'weight'});
+---------------------------------------------------------------------------------+
| loadMillis | computeMillis | writeMillis | nodes  | iterations | communityCount |
+---------------------------------------------------------------------------------+
| 90029      | 1893360       | 3918        | 900558 | 5          | 83023          |
+---------------------------------------------------------------------------------+

b) The non-projected query with weight property throws an error.

CALL algo.louvain('Network_L1_Louvain','INTERACTED',{ weightProperty:'amt',defaultValue:0.0, concurrency:1, write:true, writeProperty:'partition_test2'});
**Failed to invoke procedure `algo.louvain`: Caused by: java.lang.ArrayIndexOutOfBoundsException: -1**


Would appreciate any insights into this. Thanks!

**Comment by mknblch** [comment]
Thanks for the info im going to check the exception. Can you take a look into the neo4j-logs to see how far the algorithm went? Louvain reports inner and outer iteration counts. The "inner" count is the current node index. Once it hits the maximum nodecount an outer iteration starts and rebuilds a virtual graph based on the new community structure. This resumes as long as the modularity increases.

Also the logic of the louvain algorithm changed slightly in the last update. It now iterates over the nodes in random order. This is meant to be done in parallel. In the end of each round the best thread with the highest modularity is taken and used for the next round (if any). You could therefore increase the concurrency param so it actually does more then one try. I will also add a config flag to turn random order on or off. And i think its a good idea to turn it off by default if concurrency is set to 1.

**Comment by aforadi** [comment]
This I what I see in the logs for the error run.

2018-09-10 23:49:39.454+0000 INFO [o.n.k.i.p.Procedures] [HugeNodeImporter-2114622525] LOADING 0%
2018-09-10 23:49:45.922+0000 INFO [o.n.k.i.p.Procedures] [neo4j.BoltWorker-5 [bolt] [/127.0.0.1:59788] ] LOADING 100%
2018-09-10 23:49:45.931+0000 INFO [o.n.k.i.p.Procedures] [neo4j.BoltWorker-5 [bolt] [/127.0.0.1:59788] ] Louvain 0% Init
2018-09-10 23:49:46.321+0000 INFO [o.n.k.i.p.Procedures] [neo4j.BoltWorker-5 [bolt] [/127.0.0.1:59788] ] Louvain 100% Init complete
This is from debug.log.

As far as parallelism, my algorithm wouldn't finish running if I used concurrency greater than 1 and would run indefinitely. I assumed this was related to issue #558.

Any inputs regarding the other issues? Why am I getting different number of communities for the 2 runs? Why does using the wight property not change my results? Thanks!

**Comment by mneedham** [comment]
@aforadi  are you using the version of Louvain from master or the latest released version? We've done some big changes on the master so it'd help to try and narrow down what the issue is...

Also if you're able to provide us with a small graph that reproduces the issue then we'll be able to fix it more easily.

**Comment by aforadi** [comment]
@mneedham  I am using  neo4j-community-3.4.4 with graph-algorithms-algo-3.4.4.0.jar

Let me try and see if I can reproduce the issue with a simpler graph.

**Comment by mneedham** [comment]
@aforadi ok cool, that'd be helpful.

Also in the latest release (3.4.7.0) we have multi stage Louvain so maybe give that a try while you're in the area!
