### ISSUE TITLE
Considerations on weights

### ISSUE THREAD

**Issue by mknblch** [neo4j-contrib/neo4j-graph-algorithms#73]
So far we assumed edge weights to be double values in [0, 1) and we have a basic mapper logic for turning arbritary property objects into doubles. We also have to duplicate the relationship-iterator ifaces for the weighted versions. This make the handling of weights very inflexible. With the api2 approach we could consider to switch over to a weight-datasource instead of haven them bound to the iterator. 

Since we consider one property per relation and one relation between a pair of nodes we could use the mapped-nodeIds as key-pair. 

I'd suggest something like this
```
wheightOf(sourceNodeId:int, targetNodeId:int):double
```

This would reduce the amount of different ifaces and implementations. We could also have different impl. for the wheight-source with their own characteristics.

**Comment by jexp** [comment]
We could even map weights to integers to save memory. Eg with a multiplier 

Von meinem iPhone gesendet

**Comment by mknblch** [comment]
Already implemented

**Comment by mknblch** [comment]
already implemented
