### ISSUE TITLE
RandomWalk algorithm isn't available to me in jar file 3.4.7

### ISSUE THREAD

**Issue by MohamedElbanna** [neo4j-contrib/neo4j-graph-algorithms#733]
I downloaded the jar file of algorithms implementation from the latest release location on github and tested most of them they worked well except for randomwalk algorithm is not listed with the other algorithms and when trying to run the code it gives me error Neo.ClientError.Procedure.ProcedureNotFound: There is no procedure with the name `algo.randomWalk.stream` registered for this database instance. Please ensure you've spelled the procedure name correctly

**Comment by tomasonjo** [comment]
try the release from 19 days ago, I tried it and it works

https://github.com/neo4j-contrib/neo4j-graph-algorithms/releases/download/3.4.7.0/graph-algorithms-algo-3.4.7.0.jar
