### ISSUE TITLE
graph-algorithms plugin v 3.4.8.0 is not working with Neo4j 3.4.8 on neo4j desktop

### ISSUE THREAD

**Issue by miromarchi** [neo4j-contrib/neo4j-graph-algorithms#739]
Reproduce:
use Neo4j desktop 1.1.10 macOs
create a 3.4.7 database with algo plugin
upgrade to 3.4.8
error is `Failed to upgrade database: DB [database-uuid] 'v3.4.8' exited with status 'KILLED'`
check plugins, see that algo is also 3.4.8.0.
(I also tried to uninstall and reinstall algo, with no success).

**Comment by mneedham** [comment]
I tried these scenarios locally and both were ok:

* Install 3.4.8, Add plugin, Run Page Rank
* Install 3.4.7, Add plugin, Upgrade, Run Page Rank

Are there any other logs in logs/neo4j.log or logs/debug.log?

**Comment by mneedham** [comment]
This version of desktop: 

> Version 1.1.10 (1.1.10.894)

**Comment by miromarchi** [comment]
Hi mark, thanks for watching this out. 
The error I get when starting the upgraded db is 
```ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@bafc754' was successfully initialized, but failed to start. Please see the attached cause exception "Unable to register procedure, because the name `algo.unionFind.mscoloring` is already in use.". ```

**Comment by miromarchi** [comment]
Sorry @mneedham I didn't see your last comment, cannot answer anymore (I do not remember).
