### ISSUE TITLE
 java.lang.ClassNotFoundException with algo.pageRank

### ISSUE THREAD

**Issue by soulhound** [neo4j-contrib/neo4j-graph-algorithms#751]
I am a windows user, and I have trouble with the pagerank method.

Query run : "CALL algo.pageRank('Page', 'LINKS',{ iterations:20, dampingFactor:0.85, write: true, writeProperty:"pagerank"})", which is directly copied from the manual page
https://neo4j.com/docs/graph-algorithms/3.4/algorithms/page-rank/

Error message is as below
----
Neo.ClientError.Procedure.ProcedureCallFailed
Neo.ClientError.Procedure.ProcedureCallFailed: Failed to invoke procedure `algo.pageRank`: Caused by: java.lang.ClassNotFoundException: org.neo4j.internal.kernel.api.exceptions.KernelException
----

JDK installed version is jdk-11.0.1
JRE installed version is jre1.8.0_191

Neo4j Browser version is 3.2.11
Neo4j Database version is 3.3.5

Graph algorithm version is graph-algorithms-algo-3.5.0.1, downloaded directly from github.

Everything is up to date, and I am not sure what I am missing. JAVA path is correctly pointing to the newest JDK folder.

Any help is very much appreciated.

**Comment by tomasonjo** [comment]
If you are using Neo4j 3.3.x, you need to use the matching graph algos release, as the algo releases for 3.4.x or 3.5.x will not work on Neo4j 3.3.x.

Here is the latest release for 3.3.x:
https://github.com/neo4j-contrib/neo4j-graph-algorithms/releases/tag/3.3.5.0

You also need to add the following to the neo4j.conf

`dbms.security.procedures.unrestricted=algo.*`

If this doesn't work, please check out also https://stackoverflow.com/questions/42286508/apoc-is-only-partially-installing-its-extension-in-neo4j-one-procedure/42357481#42357481

**Comment by soulhound** [comment]
> If you are using Neo4j 3.3.x, you need to use the matching graph algos release, as the algo releases for 3.4.x or 3.5.x will not work on Neo4j 3.3.x.
> 

It worked like a charm; and as it turns out, that is stated at the library main page! I should really start reading the manual. Thanks for the help!
