### ISSUE TITLE
Out of memory error on all of algo procedures

### ISSUE THREAD

**Issue by Legolash2o** [neo4j-contrib/neo4j-graph-algorithms#754]
I keep getting the following error not matter what procedure I call. The two nodes are right next to each other with only a single edge.

Neo.ClientError.Procedure.ProcedureCallFailed: Failed to invoke procedure `algo.kShortestPaths`: Caused by: java.lang.OutOfMemoryError: Java heap space

k-ShortestPath
**MATCH** (start:Node {UID: 1521505816}),(end:Node {UID: 104733})
**CALL** algo.kShortestPaths(start, end, 1, 'Length',{direction:'OUT', defaultValue:1.0})
**YIELD** resultCount
**RETURN** resultCount

A*
**MATCH** (start:Node {UID: 325688456}),(end:Node {UID: 104788})
**CALL** algo.shortestPath.astar.stream(start, end, 'Length', 'Latitude', 'Longitude', {defaultValue:1.0})
**YIELD** nodeId, cost
**RETURN** algo.getNodeById(nodeId).name as station,cost

I have two Nodes with UID (unique) and a Railway edge with a property Length.

**Neo4j:** 3.4.9
**Algo:** 3.4.8.0 and 3.5.0.1

**Comment by jexp** [comment]
How many nodes and relationships do you have in your graph.
How much heap memory do you have configured on your Neo4j instance?

**Comment by Legolash2o** [comment]
269792091 nodes, 492489350 relationships and about 10GB heap. The database is 112GB.

**Comment by jexp** [comment]
The library is meant to represent the graph in memory for repeated and more complex operations.

If you just need a one-off you can just use the apoc.algo.astar or dijkstra algorithms which run direclty on the data.

https://neo4j-contrib.github.io/neo4j-apoc-procedures/#_graph_algorithms_work_in_progress

Do you have an index on `:Node(UID)` ?

**Comment by Legolash2o** [comment]
I have massively reduced my data set but ran into another issue. I will close this thread.
