### ISSUE TITLE
ArticleRank prints all values to console

### ISSUE THREAD

**Issue by timholds** [neo4j-contrib/neo4j-graph-algorithms#755]
When running articlerank streaming algorithm, it seems to print all the values out to the console. 
![image](https://user-images.githubusercontent.com/24782018/48380102-61c5dd80-e68b-11e8-9e0a-1225e28dd153.png)

**Comment by mneedham** [comment]
@timholds is it still doing this on the latest version? I tried running it and I don't see any printing...also didn't spot any sys.outs in the code
