### ISSUE TITLE
articleRank returns error

### ISSUE THREAD

**Issue by tomasonjo** [neo4j-contrib/neo4j-graph-algorithms#759]
Create graph:
```

MERGE (paper0:Paper {name:'Paper 0'})
MERGE (paper1:Paper {name:'Paper 1'})
MERGE (paper2:Paper {name:'Paper 2'})
MERGE (paper3:Paper {name:'Paper 3'})
MERGE (paper4:Paper {name:'Paper 4'})
MERGE (paper5:Paper {name:'Paper 5'})
MERGE (paper6:Paper {name:'Paper 6'})

MERGE (paper1)-[:CITES]->(paper0)

MERGE (paper2)-[:CITES]->(paper0)
MERGE (paper2)-[:CITES]->(paper1)

MERGE (paper3)-[:CITES]->(paper0)
MERGE (paper3)-[:CITES]->(paper1)
MERGE (paper3)-[:CITES]->(paper2)

MERGE (paper4)-[:CITES]->(paper0)
MERGE (paper4)-[:CITES]->(paper1)
MERGE (paper4)-[:CITES]->(paper2)
MERGE (paper4)-[:CITES]->(paper3)

MERGE (paper5)-[:CITES]->(paper1)
MERGE (paper5)-[:CITES]->(paper4)

MERGE (paper6)-[:CITES]->(paper1)
MERGE (paper6)-[:CITES]->(paper4)

```

Run algo:

```
CALL algo.articleRank.stream('Paper', 'CITES', {iterations:20, dampingFactor:0.85})
YIELD nodeId, score
RETURN algo.getNodeById(nodeId).name AS page,score
ORDER BY score DESC

```

returns error:

> Neo.ClientError.Procedure.ProcedureCallFailed: Failed to invoke procedure `algo.articleRank.stream`: Caused by: java.lang.NoClassDefFoundError: com/codahale/metrics/MetricRegistry

**Comment by mneedham** [comment]
Hmmm...in theory that class should be supplied by Neo4j. Which version of Neo were you running against out of interest?

**Comment by tomasonjo** [comment]
First I was using neo 3.4.7, but I tried it now on fresh neo 3.4.10 and it returns the same error

**Comment by tomasonjo** [comment]
Tried on enterprise aswell and it works... the problem seems to be community server where this package is not available

**Comment by mneedham** [comment]
Ah! That makes sense. I think Neo4j only uses the library for the metrics stuff which is only in the enterprise version. Let me figure out a better way to depend on that library

**Comment by tomasonjo** [comment]
fixed with https://github.com/neo4j-contrib/neo4j-graph-algorithms/commit/b9fb0584515b5c5d094fc0e156061598b438d7e5
