### ISSUE TITLE
Unable to run connected components on a large graph

### ISSUE THREAD

**Issue by chinkitp** [neo4j-contrib/neo4j-graph-algorithms#785]
## Environment
- neo4j v 3.5
- graph-algorithms-algo v 3.5.0.1
- apoc v 3.5.0.1
- AWS R5.24xlarge: 96 vCPU & 748GB RAM with SSD

Please see the log file for configuration changes

## Graph
My graph is the bitcoin address graph whose degree distribution is the classic power-law.

- 639,204,230 Nodes (Addresses & Transactions)
- 741,853,556 Edges ```(a:address)-[e:INPUT_TO]->(t:transaction)```

## Cypher Query
```
CALL algo.unionFind.stream(null, null, {})
YIELD nodeId,setId
```
Running this from cypher-shell re-directing the output to a local file.

## Error
[neo_log.txt](https://github.com/neo4j-contrib/neo4j-graph-algorithms/files/2739485/neo_log.txt)

**Comment by jexp** [comment]
What is your configuration for heap + page-cache?

**Comment by jexp** [comment]
Ah found it:

- dbms.memory.pagecache.size=706600m
- dbms.memory.heap.max_size=500g

is in total more than your available memory?
Can you configure it so that  you use e.g. 250g for heap and 450g for page-cache
and try again?

**Comment by chinkitp** [comment]
> Ah found it:
> 
> * dbms.memory.pagecache.size=706600m
> * dbms.memory.heap.max_size=500g
> 
> is in total more than your available memory?
> Can you configure it so that you use e.g. 250g for heap and 450g for page-cache
> and try again?

**Comment by chinkitp** [comment]
@jexp oops! Thanks for pointing out. I will give it a try.

**Comment by chinkitp** [comment]
Config has been changed to
```
dbms.memory.heap.initial_size=250g
dbms.memory.heap.max_size=250g
dbms.memory.pagecache.size=450g
```
I am now running with this, however the CPU is hardly utilised and the log is intermittently showing _Detected VM stop-the-world pause_. See attached log file. 

Happy to leave it running for another few hours and report back with a full log. 
[neo_log2.txt](https://github.com/neo4j-contrib/neo4j-graph-algorithms/files/2742906/neo_log2.txt)

**Comment by jexp** [comment]
Oh something I forgot, you might have not a lot of fun running that with cypher shell as it buffers all results.

either run it with a client that can consume the results streamingly 
or use the non-stream variant and write to the graph.

if you see too many gc pauses, you could increase teh heap a bit (by 100G) and reduce page-cache accordingly.
Or reduce the concurrency with a `concurrency: 64` config setting in the procedure call.

**Comment by chinkitp** [comment]
Changed the query as below
```
CALL algo.unionFind.stream(null, null, {concurrency:64, write:true, partitionProperty:"partition"})
YIELD nodeId,setId;
```
This has been running for 3.5 hrs now and most of the CPU's are working hard. However, I am getting the below error in the logs. See attached full logs. Should I keep it running?
```
Caused by: org.neo4j.bolt.messaging.BoltIOException: Bolt connection [/127.0.0.1:50136] will be closed because the client did not consume outgoing buffers for 00:15:00.000 which is not expected.
	at org.neo4j.bolt.v1.transport.ChunkedOutput.flush(ChunkedOutput.java:136)
	at org.neo4j.bolt.v1.transport.ChunkedOutput.messageSucceeded(ChunkedOutput.java:105)
	at org.neo4j.bolt.v1.messaging.BoltResponseMessageWriterV1.packCompleteMessageOrFail(BoltResponseMessageWriterV1.java:105)
	at org.neo4j.bolt.v1.messaging.BoltResponseMessageWriterV1.write(BoltResponseMessageWriterV1.java:79)
	at org.neo4j.bolt.v1.messaging.ResultHandler$1.visit(ResultHandler.java:47)
```
[neo_log3.txt](https://github.com/neo4j-contrib/neo4j-graph-algorithms/files/2743528/neo_log3.txt)

**Comment by jexp** [comment]
Sorry, the "non-stream" version. Without the *stream* suffix.

`CALL algo.unionFind(null, null, {concurrency:64, write:true, partitionProperty:"partition"})`

**Comment by chinkitp** [comment]
@jexp  & @tomasonjo thanks heaps for your help, I have had success now. 
```
nodes, setCount, loadMillis, computeMillis, writeMillis
639204230, 161073321, 322218, 624012, 8249024
```
I can also confirm the accuracy of the algorithm as the exact partitions were created using other methods.
