### ISSUE TITLE
Unknown function 'algo.getNodeById' 

### ISSUE THREAD

**Issue by jonathanballs** [neo4j-contrib/neo4j-graph-algorithms#786]
I am getting a syntax error when I try to use algo.getNodeById. I have it unrestricted in `dbms.security.procedures.unrestricted` and other graph functions seem to work. Why is it not available? I can't seem to find documentation on this function, it just seems to be used in a lot of examples.

```
Neo.ClientError.Statement.SyntaxError
Neo.ClientError.Statement.SyntaxError: Unknown function 'algo.getNodeById' (line 5, column 8 (offset: 286))
"RETURN algo.getNodeById(nodeId).id as user, community"
                ^
```

**Comment by jexp** [comment]
which version of the library are you using?

can you show your config entries for whitelisting and sandboxing?

**Comment by jexp** [comment]
I basically just have this:

`dbms.security.procedures.unrestricted=apoc.*,algo.*`

**Comment by mneedham** [comment]
I think this one is only included in versions 3.4 and above of the library

**Comment by jonathanballs** [comment]
I have version `3.4.4` from 6 months ago but I will try updating anyway. As far as I can see the function was created at the [end of july last year](https://github.com/neo4j-contrib/neo4j-graph-algorithms/commits/a2ae103b19e92c82bee158a505487e5529203e97/algo/src/main/java/org/neo4j/graphalgo/GetNodeFunc.java) so it may not have made it into `3.4.4`, `3.4.7` seems to be the latest release after that. I'll report back with results.

**Comment by jonathanballs** [comment]
It appears that the update from 3.4.4 to 3.5 has fixed my issue. Thank you very much.

**Comment by jaydenljh** [comment]
I was on version 3.5.0 and had the same error. Updating to 3.5.4 fixed it.
