### ISSUE TITLE
Allow other procedures to use graphalgo-core

### ISSUE THREAD

**Issue by GittiHab** [neo4j-contrib/neo4j-graph-algorithms#802]
It would be awesome if other procedures could use the graphalgo-core as a maven dependency and build on the efficient api.

**Comment by mneedham** [comment]
We do publish that on Maven as well - https://search.maven.org/search?q=g:org.neo4j%20AND%20a:graph-algorithms-core&core=gav

So you could include that and build on top of it if you want
