### ISSUE TITLE
Support undirected PageRank

### ISSUE THREAD

**Issue by szarnyasg** [neo4j-contrib/neo4j-graph-algorithms#845]
I am working to implement the [LDBC Graphalytics](http://graphalytics.org/) workload using the Graph algorithms library. This requires implementing the undirected variant of PageRank (PR).

The [specification](https://ldbc.github.io/ldbc_graphalytics_docs/graphalytics_spec.pdf) defines PR as follows:

![image](https://user-images.githubusercontent.com/1402801/54738011-b1c12d80-4bb2-11e9-8db6-9a036961e281.png)

The example graph and the expected output are listed in the Graphalytics repository as [`pr/undir-input`](https://github.com/ldbc/ldbc_graphalytics/blob/master/graphalytics-validation/src/main/resources/validation-graphs/pr/undir-input) and [`pr/undir-output`](https://github.com/ldbc/ldbc_graphalytics/blob/master/graphalytics-validation/src/main/resources/validation-graphs/pr/undir-output).

It's worth noting that most graphs in the basic Graphalytics data set are undirected (29 out of 33):

```console
ag 'directed = false' -l | wc -l
29
```

**Comment by tomasonjo** [comment]
We already support undirected pageRank. I just updated the docs yesterday https://github.com/neo4j-contrib/neo4j-graph-algorithms/commit/aaf6a2c6c336cae9eda0d351151e6734907ff48b. You need to use `direction:'BOTH'` when treating the graph as undirected

**Comment by szarnyasg** [comment]
Indeed, there is support for undirected PageRank. Thanks!
