### ISSUE TITLE
algo.degree breaks when degree > 10000

### ISSUE THREAD

**Issue by tomasonjo** [neo4j-contrib/neo4j-graph-algorithms#848]
example graph:

```
UNWIND range(1,10005) as s
CREATE (:Node{id:s});

MATCH (n:Node)
WITH n limit 1
MATCH (m:Node)
WHERE id(n) <> id(m)
CREATE (m)-[:REL]->(n);
```

Run the algo:

```
CALL algo.degree.stream("Node", "REL", {direction: "incoming"})
YIELD nodeId, score
RETURN algo.getNodeById(nodeId).id AS name, score AS followers
ORDER BY followers DESC
```

Error:

> Neo.ClientError.Procedure.ProcedureCallFailed: Failed to invoke procedure `algo.degree.stream`: Caused by: java.lang.ArrayIndexOutOfBoundsException: 10000

**Comment by Nulleye** [comment]
I have a similar issue, I think I've solved it by adding the starts... line in the for loop in the compute() funtion on DegreeCentrality.java class. I think the starts array is not correctly initialized.
Maybe someone can check this out and create a pull request?

```
 public void compute() {
        ...
        for (int i = 0; i < taskCount; i++) {
        	starts[i] = (long) batchSize * i;
```

**Comment by mneedham** [comment]
I think this commit fixes it (by doing pretty much the same thing)

https://github.com/neo4j-contrib/neo4j-graph-algorithms/commit/81c8bfb0d7acabb8f2d9eae4f9dcc4b8fc914d9d
