### ISSUE TITLE
potential bug in pagerank: unsteady value

### ISSUE THREAD

**Issue by sarmbruster** [neo4j-contrib/neo4j-graph-algorithms#861]
It seems that PageRank has some overflow issue. 

In a slowly growing network (10-100k rels per day added) with some very dense nodes (>16M rels) every day pagerank is calculated. See below  a diagram how pagerank evolved over time. For the blue line (representing one of the very dense nodes) we see a massive drop of its pagerank two times. This behaviour "smells" like being a kind of overflow error.

<img width="1069" alt="Bildschirmfoto 2019-03-27 um 09 35 19 (1)" src="https://user-images.githubusercontent.com/106522/55177665-0ac92c80-5184-11e9-9447-0d035f7586b5.png">

**Comment by Mats-SX** [comment]
@sarmbruster Did you have a chance to verify whether #872 addressed this issue? We'd like to close it if so, otherwise we'll need a new investigation.

**Comment by sarmbruster** [comment]
Don't remember 100% but I think I've tested it back in May and it did work. So let's close it and reopen if issue persists.
