### ISSUE TITLE
Docs: Shortest Path and Single Source Shortest Path refer to the same algorithm

### ISSUE THREAD

**Issue by Mona144** [neo4j-contrib/neo4j-graph-algorithms#892]
I noticed that at one point in the [docs](https://neo4j.com/docs/graph-algorithms/3.5/algorithms/pathfinding/) both Shortest Path and Single Source Shortest Path refer to the same algorithm
```
Shortest Path (algo.shortestPath)
Single Source Shortest Path (algo.shortestPath)
```
I also noticed that this is not the case [here](https://github.com/neo4j-contrib/neo4j-graph-algorithms), which I assume is correct
```
Shortest Path (algo.shortestPath)
Single Source Shortest Path (algo.shortestPath.deltastepping)
```

**Comment by jjaderberg** [comment]
Thanks @Mona144 this is fixed, and the updated docs will be published soon.
