### ISSUE TITLE
run algo on apoc virtual graph? From apoc virtual graph to named graph

### ISSUE THREAD

**Issue by tonny008** [neo4j-contrib/neo4j-graph-algorithms#914]
hot to run algo on apoc virtual graph? ways to convert apoc virtual graph to a named graph

**Comment by AliciaFrame** [comment]
We don't recommend running algorithms on apoc virtual graphs. 

If you're using apoc virtual graphs to project a document into a graph, you'll want to import the data into neo4j and then run graph algorithms on the graph itself. If you're using virtual graphs to reshape the data in an existing neo4j instance into a different projection, you can use the cypher projections in the graph algorithms package (https://neo4j.com/docs/graph-algorithms/current/projected-graph-model/cypher-projection/).
