### ISSUE TITLE
Maven release

### ISSUE THREAD

**Issue by azocankara** [neo4j-contrib/neo4j-graph-algorithms#919]
We use the maven release to include the procedures in neo4j embedded for our tests. 

The latest maven release is for version 3.5.4.0, is there a reason why new releases are not published to maven ?

**Comment by Mats-SX** [comment]
Hello @azocankara and thanks for reaching out.

We (Neo4j) are in the process of building an official product based off of this project. This involves among other things a rehoming of the project sources, which are currently not open source. We have recently decided how we will surface this, and I'll reach back here when I have a link to the new sources to give you.

In terms of actual binaries, we have stopped publishing to Maven for now, but once we get closer to our actual release date for the new product 1.0 we will start to do that again. Until that time, you can find our latest release in the Neo4j Download Center: https://neo4j.com/download-center/#algorithms as well as in Neo4j Desktop (using the Graph Algorithms plugin).

**Comment by Mats-SX** [comment]
A little later than planned, but the new product sources are now live at https://github.com/neo4j/graph-data-science

Maven releases will come as part of our upcoming release(s), publicised from the new repository.
