### ISSUE TITLE
Keeping track of traversed properties

### ISSUE THREAD

**Issue by cbobed** [neo4j-contrib/neo4j-graph-algorithms#923]
Hi, 

I'm currently writing an extension of the RandomWalk procedure in order to keep track the traversed properties as well (instead of adding virtual ones). However, while there is a method to translate the nodeIds of the loaded graph to the nodeIds in the original one, there is no such a similar method for relationships (or at least I haven't found it). 

So far, it seems that if I wanted to do so, I would have to extend the Graph interface, and at least extend the implementation of one of the graph implementations (probably the most sensible one to start from would be HeavyGraph). Am I in the correct track? Is there any further detail I should borne in mind if I tackle this task? 

Another possible way to approximate what I'm looking for would be to calculate the paths, and afterwards, calculate the probability of each edge taking a look into the original graph, but this would not reflect the actual random walks generated.

Best

**Comment by AliciaFrame** [comment]
Hi @cbobed - we just open sourced the updated, product supported code for the graph data science library, ahead of our preview release in February. You'll want to check out: https://github.com/neo4j/graph-data-science for the most up to date code, and the best place to post issues.
