### ISSUE TITLE
Neo4j 4.0 support?

### ISSUE THREAD

**Issue by fuvidani** [neo4j-contrib/neo4j-graph-algorithms#924]
Hi,

Are there any short-term plans for Algo to support/be compatible with the recent Neo4j 4.0 version?  For the record, I did try to run a fresh 4.0.0 container with algo 3.5.14.0 plugin, but unfortunately the database crashes after a few seconds presumably due to recent (breaking) changes in the latest release (it runs without no issues if I remove the algo plugin).

Any information would be much appreciated. :) 

Cheers,
Daniel

**Comment by AliciaFrame** [comment]
The graph algorithms library is not, and won't be, compatible with Neo4j 4.0.

We'll be releasing a new, product supported Graph Data Science library in the next month (stay tuned!) that will replace the current graph algorithms library, and it includes versions of all the current algorithms as well as lots of exciting new features and enhancements. **We're currently planning to offer a 4.0 compatible version of the graph data science library by April 2020**, so stay tuned :)

**Comment by AliciaFrame** [comment]
The graph algorithms library is not, and won't be, compatible with Neo4j 4.0.

We'll be releasing a new, product supported Graph Data Science library in the next month (stay tuned!) that will replace the current graph algorithms library, and it includes versions of all the current algorithms as well as lots of exciting new features and enhancements. **We're currently planning to offer a 4.0 compatible version of the graph data science library by April 2020**, so stay tuned :)
