### ISSUE TITLE
Compatibility with Neo4j V4.0

### ISSUE THREAD

**Issue by mnitin73** [neo4j-contrib/neo4j-graph-algorithms#926]
Is the graph-algorithms compatible with neo4j 4.0? Version 4 is not mentioned in the compatibility matrix and I am not able to load it as a plugin. The neo4j server crashes when I include the jar in the plugins folder.
How do I use algorithms with Neo4j Ver4. I am using the community edition.

Thanks.

**Comment by AliciaFrame** [comment]
No, the graph algorithms library is not currently compatible with Neo4j 4.0, and we do not have plans to update this library to make it compatible in the future.

We are in the process of releasing the new graph data science (GDS) library -- the preview release will be posted on our[ download center](https://neo4j.com/download-center/) tomorrow on 2/6, or the open source repo is at https://github.com/neo4j/graph-data-science. Our ongoing development work will be focused on the GDS, with all new algorithms, enhancements, bug fixes, etc released as part of this library.  The GDS includes all algorithms in the current graph algorithms library.

**The GDS library is not currently compatible with Neo4j 4.0, but we are planning a 4.0 compatible release in mid Q2 (April/May) so stay tuned** 🙂
