### ISSUE TITLE
Releases tab is misleading

### ISSUE THREAD

**Issue by Liczi** [neo4j-contrib/neo4j-graph-algorithms#927]
The releases tab is quite misleading (https://github.com/neo4j-contrib/neo4j-graph-algorithms/releases) as the `latest` tag points to an old version of the plugin. Please consider updating or disabling that.

Also, from README:
> Our current version is 3.5.13.0

which is not correct latest as well.

**Comment by AliciaFrame** [comment]
As we state in the readme, the best place to look for the most recent jar is on the neo4j download center, and we stopped making use of this repo for our releases as of 3.5.4. I've updated the readme to note the current version is 3.5.13.

We are in the process of releasing the new graph data science (GDS) library -- the preview release will be posted on our [download center](https://neo4j.com/download-center/) tomorrow on 2/6, or the open source repo is at https://github.com/neo4j/graph-data-science. 

Future issues should be files on that repo, or if you are building your own algorithms, start from that codebase.
